### PR TITLE
DB: more testing

### PR DESCRIPTION
**Pull request by boyska**
In this pull request I am merely adding new unit tests, to increase the coverage of DB api.

To test it, you should:
* check the code, to understand if the check I wrote are meaningful
* run the test suite, to ensure they pass!

### CODE REVIEW

**Comment by ael-code** [comment]
can you rebase this PR in order to include 7b9bbce. It will be easier to test for me without errors.

**Comment by boyska** [comment]
@ael-code rebased

**Comment by ael-code** [comment]
```test_update_download_count()``` do not test against a standard database entry format, so noone ensure that it will continue to work in future.

```test_update_download_count()``` tests only one download count increment, isn't better to test more increment ?

The other changes seems correct.

**Comment by boyska** [comment]
On Wed, Mar 04, 2015 at 05:44:23AM -0800, ael wrote:
>```test_update_download_count()``` do not test against a standard database entry format, so noone ensure that it will continue to work in future.

I don't really understand this. That's the way it works **now**. I agree
it is not documented, so there's no guarantee to continue to work in future.
But unit tests are not API documentation, they are a documentation of
how the real code is working. If we change the entry format, we'll
change unit tests too; but at least we would notice it immediately.

Now I added a test that is even more clear about how the code works
right now, and its gotchas.

>```test_update_download_count()``` tests only one download count increment, isn't better to test more increment ?

fixed

**Pull request merged**
