### PR TITLE
User CLI

### LINKED ISSUE #77: User admin command
We should be able to do basic user operations through libreant-manage:
* user_add
* users_list
* user_perm_list
* user_perm_add

This is similar to #78, but will be probably much easier to implement.

This depends on #6 and #74

### PR DESCRIPTION
**Pull request by boyska**
This fixes #77. It provides a new command `libreant-users` which provides several command to manage users. I think there is every action possibly needed for administering users.

The output style is, similarly to `libreant-db`, outputting a JSON representation of the "interested" object. So for example when you create a user, the user object will be printed.

The first commit extend the models, so now there is a specific `ActionField` which makes action handling easier. Also, every model now has a `to_dict()` method.

I remember that the choice of both naming and goal of this method was debated, and I am not sure that I remember it correctly. So please point out what I'd better change, if so.

### CODE REVIEW

**Comment by ael-code** [comment]
Travis failed on this PR

**Comment by boyska** [comment]
ael wrote:
>Travis failed on this PR

ooops!
The offending commit is the first one, which messes with peewee Fields

**Comment by boyska** [comment]
@ael-code it should be fixed now. If you are curious, I removed the `Meta` class inside `UserToGroup` and `GroupToCapability`. I can't understand **why** I did it, but I am glad that unit tests prevented this to sneak inside. I revert those part of the pull request, plus fixing some flake warning. Now everything works.

**Comment by ael-code** [comment]
All commands works without the need of --users-database param.
If we don't set the --users-database param we will work on a sqlite in memory database.

I think that you didn't notice that cause of the lack of logging for the users module.

**Comment by ael-code** [comment]
I think that the organization of the commands are quite chaotic, all operations have their own primary sub-command.
What do you think about something like:

```
libreant-users group:
-l, --list         list all groups
-a, --add      add new group
-d, --delete  delete a group
...


libreant-users user:
-l, --list         list all users
-a, --add      add user
-d, --delete  delete user
...
```

**Comment by boyska** [comment]
ael wrote:
>I think that the organization of the commands are quite chaotic, all
>operations have their own primary sub-command.
>What do you think about something like:
>
>```
>libreant-users group:
>-l, --list         list all groups

This is basically using options as subcommands, which I don't like.
If click supports subsubcommand then we might do sth like:

```
libreant-users group list
libreant-users group add
libreant-users group delete
```

If it does not, we might be stricter on the same convention with
underscores, so creating subcommand like `user_passwd` or
`group_delete`.

**Comment by boyska** [comment]
ael wrote:
>All commands works without the need of --users-database param.
>If we don't set the --users-database param we will work on a sqlite in memory database.
>
>I think that you didn't notice that cause of the lack of logging for the users module.

I think that environment variables work fine. Now I have no time for
testing it, but I remember that I did. Plus, I am gonna backport the
pull request you made for --users-database. Stay tuned, I am going to
make you angry!

**Comment by ael-code** [comment]
##### Users-db option:
> I actually meant: I am going to do it, but **not** in this pull request. I think that for the moment the environment variable is enough, but I will soon fix it. 

I think it's not working. Users database url option for this command should be mandatory.
As I already wrote:
> If we don't set the --users-database param we will work on a sqlite in memory database.

##### Subcomamnd organization:
> About the subcommand naming/organization, if you can give me some feedback I'd be glad to redesign them.

I like the form you suggested:
```
libreant-users group list
libreant-users group add
libreant-users group delete
...
```

**Comment by boyska** [comment]
On Tue, Nov 10, 2015 at 02:59:05AM -0800, ael wrote:
>##### Users-db option:
>> I actually meant: I am going to do it, but **not** in this pull request. I think that for the moment the environment variable is enough, but I will soon fix it.
>
>I think it's not working.

It is working, I am pretty sure. If it does not work for you, we have
found a bug.

```
LIBREANT_USERS_DATABASE=sqlite:////tmp/asd.db libreant-users lsusers
```

>Users database url option for this command should be mandatory.

ok...

>As I already wrote:
>> If we don't set the --users-database param we will work on a sqlite in memory database.

...still, this is false

**Comment by boyska** [comment]
**-kaos**: I refactored the command in subsubcommand, trying to achieve some coherence. So for example I used the words _create/delete_ when new users/groups are created. The words _add/remove_ are about removal of something from a set (that is, removing a user from a group).

The capability thing is the strangest of all: deleting a capability is not, logically, a subcommand of group. The adding of a capability should have followed a process similar to a user, separating the creation from the add. This was however just crazy to me, so I did the opposite.

**Comment by boyska** [comment]
any progress on this?

**Comment by ael-code** [comment]
can you split 8ee78bd61143cd690b386dbea5841230b5bd7d62 in order to have to_dict function introduction chages into their own commit? It will be easier to merge dashboard in the future :)

**Comment by boyska** [comment]
the docstring about ActionField has been fixed, `list_to_bitmask` has been renamed to `from_list` and `to_dict` is the first commit of this changeset, so that taking only it is really simple.

**Comment by ael-code** [comment]
> the docstring about ActionField has been fixed, list_to_bitmask has been renamed to from_list and to_dict is the first commit of this changeset, so that taking only it is really simple.

The first commit make use of the `to_list()` function that is introduced in the second one commit.

**Comment by ael-code** [comment]
Some comments before I wrote:
> All commands works without the need of --users-database param.
> If we don't set the --users-database param we will work on a sqlite in memory database.
> 
> I think that you didn't notice that cause of the lack of logging for the users module.

You were pretty sure that this was false. Now that we have introduced logs also for users module,
you can have some evidence by running:
```libreant-users -d user list```
In the logging output you will see:
```[users] [DEBUG] Initializing database: {'url': 'sqlite:///:memory:', 'pwd_rounds': 29000, 'pwd_salt_size': 16}```
And this means that we are operating on sqlite in memory database.

**Comment by ael-code** [comment]
`user show` does not handle the not found exception

**Comment by ael-code** [comment]
what do you think about merging ```group caplist``` into ```group show```.

**Comment by ael-code** [comment]
How do I use ```group cap-add``` in order to add a capabilities with multiple action.
This code is black magic for me:
```
capability_add(groupname, domain, action):
    possibleactions = {v[0]: v for v in users.Action.ACTIONS}                                                                                        
    action = '' if action == '0' else action                                                                                                         
    action = [possibleactions[x] for x in action]                                                                                                    
    action = users.Action.from_list(action)
```
Can you explain it?

**Comment by boyska** [comment]
On Sun, Nov 22, 2015 at 02:49:36AM -0800, ael wrote:
>Some comments before I wrote:
>> All commands works without the need of --users-database param.
>> If we don't set the --users-database param we will work on a sqlite in memory database.
>>
>> I think that you didn't notice that cause of the lack of logging for the users module.
>
>You were pretty sure that this was false. Now that we have introduced logs also for users module,
>you can have some evidence by running:
>```libreant-users -d user list```
>In the logging output you will see:
>```[users] [DEBUG] Initializing database: {'url': 'sqlite:///:memory:', 'pwd_rounds': 29000, 'pwd_salt_size': 16}```
>And this means that we are operating on sqlite in memory database.

ok but you CAN specify the option. Or wasn't this what you were asking?
were you asking to set that option as required?

**Comment by boyska** [comment]
On Sun, Nov 22, 2015 at 02:49:36AM -0800, ael wrote:
>Some comments before I wrote:
>> All commands works without the need of --users-database param.
>> If we don't set the --users-database param we will work on a sqlite in memory database.
>
>You were pretty sure that this was false.

I AM  sure that this is false, meaning that if you set the correct
environment variable, everything works as expected.

And it works, I double-checked now:

```
% LIBREANT_USERS_DATABASE=sqlite:///tmp/asd libreant-users -d user list
2015-11-22 12:54:39,098 [users] [DEBUG] Initializing database: {'url': 'sqlite:///tmp/asd', 'pwd_rounds': 29000, 'pwd_salt_size': 16}
2015-11-22 12:54:39,098 [users] [DEBUG] Creating missing database tables
2015-11-22 12:54:40,220 [users] [DEBUG] Populating with default users
[{"name": "admin", "id": 1}, {"name": "anonymous", "id": 2}]
```

which is correct.
So there are two ways of setting users db: environment and commandline
option. Both method work.

-- 
boyska

**Comment by ael-code** [comment]
> were you asking to set that option as required?

YES

**Comment by boyska** [comment]
On Sun, Nov 22, 2015 at 03:30:58AM -0800, ael wrote:
>How do I use ```group cap-add``` in order to add a capabilities with multiple action.
>This code is black magic for me:

ok, so there is need for better documentation, sorry :)
valid values for "action" are:

* `CRUD`
* `CR` that is, create and read
* `RC` the same, order is irrelevant
* `RUC` read update create
* `RRRR` duplicates are not an issue

this is inspired from the typical linux `rwx` thing.
Empty string means no action. I did an alias for this called `0`.
`0` is equivalent to "no action" so that it is easier to type it.
Still have to figure out why an "empty action" has some sense, but still.

**Comment by boyska** [comment]
On Sun, Nov 22, 2015 at 04:00:45AM -0800, ael wrote:
>> were you asking to set that option as required?
>
>YES

but then what if you have an environment variable set? I believe that
setting environment variables should be the common way (for a sysadmin)
to do this kind of stuff.

So setting the option as _required_ is not good for me, but we could
"blacklist" the in-memory db. So that after environment reading + option
parsing, if you still are using in-memory db, a warning will be printed.

**Comment by ael-code** [comment]
> but then what if you have an environment variable set? I believe that setting environment variables should be the common way (for a sysadmin) to do this kind of stuff.

You don't need to worry about that, we already have some clever code that handles this.
You just need to check if `USERS_DATABASE` is inside the conf object ;)

**Comment by boyska** [comment]
Ok, fixed the `--users-db` thing with a warning.

**Comment by boyska** [comment]
Action-related code has been much improved: more documentation and cleaner code.

**Comment by ael-code** [comment]
> Ok, fixed the --users-db thing with a warning.

Why you did not just make it mandatory?

**Comment by boyska** [comment]
commands such as `user list` can be useful with in-memory db, so that a sysadmin can check the defaults.

**Comment by ael-code** [comment]
> Ok, fixed the --users-db thing with a warning.

Why you did not just make it mandatory?

**Comment by boyska** [comment]
> what do you think about merging ```group caplist``` into ```group show```.

sorry I didn't read this the other day. Since members are shown, what you propose seems reasonable.

I'd also add `user cap-list` (which merges the capabilities for every Group that User belongs to) because that's often what a sysadmin wants to know, but I will do this in a future pull request, since it's so low-priority

**Comment by ael-code** [comment]
> > > Ok, fixed the --users-db thing with a warning.
>  
> > Why you did not just make it mandatory?
>
> commands such as user list can be useful with in-memory db, so that a sysadmin can check the defaults.

Sorry if I'm going to stress this point. But I really don't like the warning solution.
In the average case you won't work with in-memory db and actually you don't want.
If we make mandatory the users-db param,  sysadmin and developers will always have the possibility to set the in-memory db explicitly.

**Comment by boyska** [comment]
On Wed, Nov 25, 2015 at 03:55:32AM -0800, ael wrote:
>> > > Ok, fixed the --users-db thing with a warning.
>>
>> > Why you did not just make it mandatory?
>>
>> commands such as user list can be useful with in-memory db, so that a
>> sysadmin can check the defaults.
>
>Sorry if I'm going to stress this point. But I really don't like the
>warning solution.  In the average case you won't work with in-memory db
>and actually you don't want.  If we make mandatory the users-db param,
>sysadmin and developers will always have the possibility to set the
>in-memory db explicitly.

so you are proposing that NOT specifying the users-db raise an error,
but specifying ```sqlite:///:memory:```, right? Seems reasonable.

**Comment by ael-code** [comment]
On 11/25/2015 01:03 PM, BoySka wrote:
> On Wed, Nov 25, 2015 at 03:55:32AM -0800, ael wrote:
>>Sorry if I'm going to stress this point. But I really don't like the
>>warning solution. In the average case you won't work with in-memory db
>>and actually you don't want. If we make mandatory the users-db param,
>>sysadmin and developers will always have the possibility to set the
>>in-memory db explicitly.
> 
> so you are proposing that NOT specifying the users-db raise an error,
> but specifying ```sqlite:///:memory:```, right? Seems reasonable.
> 

Yes

**Comment by ael-code** [comment]
@boyska have you planned to update this pr? I really would like to merge

**Comment by boyska** [comment]
ooops, went out of my mind, thanks for reminding me. I'll try to do something about it later.

**Comment by boyska** [comment]
hey, @ael-code , wait! It seems to me that I already fixed the "error on unspecified --users-db" that you were saying, with commit f32e11a.

Is there anything else I should do?

**Comment by ael-code** [comment]
you're completely right. I should stop to trust github about dates :)

**Comment by ael-code** [comment]
```
ERROR: --users-db not set; this will use an in-memory db, which is probably not what you want
```
Why we're telling what the program is not going to do? Actually is going to exit and that's it.

**Comment by ael-code** [comment]
What about this old comment?

> wherever you use get_* from users api you should also handle the related not found exception.
> We don't want to have stack strace on the CLI, unless we've explicitly asked for it with the --debug option.
> For example user show will print the not found stack trace on non existing user name.

**Comment by boyska** [comment]
will work on those

**Comment by boyska** [comment]
@ael-code that should be fixed

**Comment by ael-code** [comment]
I think this isn't correct:

```
$ libreant-users capability --help

ERROR: --users-db not set
```

**Comment by boyska** [comment]
I don't really know how to fix it. Any idea? The complexity of all this cases to test made me think I'll add
http://click.pocoo.org/5/testing/

**Comment by boyska** [comment]
ok, unit tests added, so that this edge-cases can be tested easily. This doesn't solve the issue about `subcmd --help`, though.

**Comment by ael-code** [comment]
I made a pr on this branch.

https://github.com/boyska/libreant/pull/1

**Comment by boyska** [comment]
Do you know that `libreant-users user --help` still raises errors, right?

**Comment by ael-code** [comment]
> Do you know that libreant-users user --help still raises errors, right?

Yeap. We can open an issue about that. 
I want to hurry up and make a new release as soon as possible, we are going too far from the latest official version.

**Comment by boyska** [comment]
Ok, I agree, was just to be sure.

**Pull request merged**
