### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by ael-code**
As asked by @g3-3k I've implemented the pagination on search page.

It's server side pagination

In the first commit I've cleaned the html template of /search and /recents that were producing weired behaviours. Look at the commit message for more details.

### CODE REVIEW

**Comment by boyska** [comment]
It seems to work fine. Two minor notes: to mean previous page/next page, you used this character [» (Right-Pointing Double Angle Quotation Mark)](http://unicode-table.com/en/search/?q=%C2%BB) which does not seem appropriate to mean pagination. I think that the word previous/next are the best solution.
Also, it would be very good to have `rel="prev"` and `rel="next"` on those same links, as per https://support.google.com/webmasters/answer/1663744?hl=it

Another small bug is that `MAX_RESULTS_PER_PAGE` is defined both in `conf/defaults.py` and `webant/webant.py` (by the way, with different values).

Also, I know why you moved to `get_books_querystring` instead of `user_search`. But wouldn't it be more correct to just add `**kwargs` to `user_search`?

**Comment by ael-code** [comment]
On 03/14/2016 01:45 AM, BoySka wrote:
> It seems to work fine. Two minor notes: to mean previous page/next page,
> you used this character » (Right-Pointing Double Angle Quotation Mark)
> <http://unicode-table.com/en/search/?q=%C2%BB> which does not seem
> appropriate to mean pagination. I think that the word previous/next are
> the best solution.

This is the proposed solution from the bootstrap guys [1], and I like it.

> Also, it would be very good to have |rel="prev"| and |rel="next"| on
> those same links, as per
> https://support.google.com/webmasters/answer/1663744?hl=it
> 

Done.

> Another small bug is that |MAX_RESULTS_PER_PAGE| is defined both in
> |conf/defaults.py| and |webant/webant.py| (by the way, with different
> values).

This is not a problem. Anyway now they share the same default value.

> 
> Also, I know why you moved to |get_books_querystring| instead of
> |user_search|. But wouldn't it be more correct to just add |**kwargs| to
> |user_search|?
> 

I've used `get_books_querystring` also in `webant/api`. Of course we can
make this change later.



[1] http://getbootstrap.com/components/#pagination-default

**Comment by boyska** [comment]
ael:
>On 03/14/2016 01:45 AM, BoySka wrote:
>> Another small bug is that |MAX_RESULTS_PER_PAGE| is defined both in
>> |conf/defaults.py| and |webant/webant.py| (by the way, with different
>> values).
>
>This is not a problem. Anyway now they share the same default value.

It is, because it makes us repeat and is confusing. Also, why is it the
case only for *this* option and for not any other?

>> Also, I know why you moved to |get_books_querystring| instead of
>> |user_search|. But wouldn't it be more correct to just add |**kwargs|
>> to |user_search|?
>
>I've used `get_books_querystring` also in `webant/api`. Of course we
>can make this change later.

Yes, that was just a note about the usage/design of libreantdb API.

**Comment by ael-code** [comment]
I would like to merge this within tomorrow (march 16). So please if you have some doubt about this, hurry-up :)

**Comment by boyska** [comment]
ael:
>I would like to merge this within tomorrow (march 16). So please if you
>have some doubt about this, hurry-up :)

I have been very clear about my concerns: the duplication of a
configuration default value is horrible :)

Apart from that, I would merge.

**Comment by ael-code** [comment]
On 03/16/2016 12:11 AM, BoySka wrote:
> ael:
>>I would like to merge this within tomorrow (march 16). So please if you
>>have some doubt about this, hurry-up :)
> 
> I have been very clear about my concerns: the duplication of a
> configuration default value is horrible :)
> 

Also ES_INDEXNAME is duplicated.
This is not an easy task. I would like to have the possibility to use
flask app without passing through the command line interface, this will
be useful for uwsgi installation. At the moment I think that this is not
well supported. Do you have a solution for that?


> Apart from that, I would merge.
>

**Comment by boyska** [comment]
ael:
>On 03/16/2016 12:11 AM, BoySka wrote:
>> ael:
>>>I would like to merge this within tomorrow (march 16). So please if you
>>>have some doubt about this, hurry-up :)
>>
>> I have been very clear about my concerns: the duplication of a
>> configuration default value is horrible :)
>>
>
>Also ES_INDEXNAME is duplicated.

but SECRET_KEY is not. So how can it work?

>This is not an easy task. I would like to have the possibility to use
>flask app without passing through the command line interface, this will
>be useful for uwsgi installation. At the moment I think that this is not
>well supported. Do you have a solution for that?

sure, just use conf.get_def_conf() instead of rewriting the same dict
inside webant/webant.py
I will submit a PR soon

**Comment by leonaard** [comment]
Tested, ok for merge.

**Pull request merged**
