### PR TITLE
compilation of translation at build time

### LINKED ISSUE #55: pip installation error v0.1
installation process performed on a clean debian.

after satisfied all dependencies and created a virtualenv,  the command  ```pip install libreant``` raise an error. This is the pip log:
```
Downloading/unpacking libreant

  Getting page http://pypi.python.org/simple/libreant
  URLs to search for versions for libreant:
  * http://pypi.python.org/simple/libreant/
  Getting page http://pypi.python.org/simple/libreant/
  Analyzing links from page https://pypi.python.org/simple/libreant/
    Skipping link https://pypi.python.org/packages/2.7/l/libreant/libreant-0.1-py2.7.egg#md5=8b667896af36333d68bf1ddd1225a9c2 (from https://pypi.python.org/simple/libreant/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/any/l/libreant/libreant-0.1.linux-x86_64.tar.gz#md5=aa2547928ad117fca8baaf44443368a9 (from https://pypi.python.org/simple/libreant/), version: 0.1.linux-x86_64
    Found link https://pypi.python.org/packages/source/l/libreant/libreant-0.1.tar.gz#md5=a36af40cfd76b6fc0ca60e41eafbb0ba (from https://pypi.python.org/simple/libreant/), version: 0.1
  Using version 0.1.linux-x86_64 (newest of versions: 0.1.linux-x86_64, 0.1)
  Downloading libreant-0.1.linux-x86_64.tar.gz

  Downloading from URL https://pypi.python.org/packages/any/l/libreant/libreant-0.1.linux-x86_64.tar.gz#md5=aa2547928ad117fca8baaf44443368a9 (from https://pypi.python.org/simple/libreant/)
  Running setup.py egg_info for package libreant

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

    IOError: [Errno 2] No such file or directory: '/home/user/libreant/ve/build/libreant/setup.py'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/home/user/libreant/ve/build/libreant/setup.py'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/user/libreant/ve/build/libreant

Exception information:
Traceback (most recent call last):
  File "/home/user/libreant/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/user/libreant/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/user/libreant/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/home/user/libreant/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/user/libreant/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/user/libreant/ve/build/libreant
```

### PR DESCRIPTION
**Pull request by ael-code**
dropped bash script in order to use pure python code.
 extended babel compile_catalog (distutils.Command) to execute compilation of translations at build time.

 included .po files in source dist package (removed the wrong .mo inclusion)

 fixes #55

### CODE REVIEW

**Comment by frenko** [comment]
I try this branch. If I try to install libreant via `./ve/bin/python setup.py develop` I get the following error:
```python
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from babel.messages.frontend import compile_catalog
ImportError: No module named babel.messages.frontend
```

**Comment by ael-code** [comment]
oke now should works

**Comment by boyska** [comment]
how should I test that it does work?
I think that

```sh
python setup.py sdist
pip install dist/libreant-0.1.tar.gz
```

should be a good test, but I am not completely sure. What have you done to test it?

**Comment by frenko** [comment]
If I using `./ve/bin/python setup.py develop` I get only this:

```
running develop
running compile_translations
error: No such file or directory
```
and if I use this
```
python setup.py sdist
pip install dist/libreant-0.1.tar.gz
```
I get this error, from pip.log:

```
running compile_translations

error: No such file or directory

----------------------------------------

Command /tmp/pr-56/ve/bin/python2 -c "import setuptools;__file__='/tmp/pip-M0vpSb-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-9PKKpm-record/install-record.txt --install-headers /tmp/pr-56/ve/include/site/python2.7 failed with error code 1 in /tmp/pip-M0vpSb-build

Exception information:
Traceback (most recent call last):
  File "/tmp/pr-56/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/tmp/pr-56/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 250, in run
    requirement_set.install(install_options, global_options)
  File "/tmp/pr-56/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1133, in install
    requirement.install(install_options, global_options)
  File "/tmp/pr-56/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 577, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/tmp/pr-56/ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /tmp/pr-56/ve/bin/python2 -c "import setuptools;__file__='/tmp/pip-M0vpSb-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-9PKKpm-record/install-record.txt --install-headers /tmp/pr-56/ve/include/site/python2.7 failed with error code 1 in /tmp/pip-M0vpSb-build
```

**Comment by ael-code** [comment]
@frenko this is very strange. are you sure that you are testing the correct commit f735395f2e50e8a34c419801cbe741a30aaf406e

you can check this executing:
```git log HEAD...HEAD~1 | head -n 1```

**Comment by frenko** [comment]
output of ``git log HEAD...HEAD~1 | head -n 1``: commit f735395f2e50e8a34c419801cbe741a30aaf406e, is this the same?
maybe something wrong in the installation??
I clone via ``git clone https://github.com/ael-code/libreant -b translations_build pr-56`` then I create virtenv using ``virtualenv -p /usr/bin/python2 --no-site-packages ve``, activated via ``source ...``. Finally I use the command previusly written. There is something wrong?

**Comment by ael-code** [comment]
### The story:

I think @boyska uploaded a bad version on pypi. He used  ```python setup.py bdist```, instead of  ```python setup.py sdist```. You can see error log on #55.
I actually don't know if is it possible to upload a working binary distribution.

After uploaded the source distribution package on pypi another problem occurred with translation build script:
```error: No such file or directory```

So I decided to change the way we compile translation.
I've made two correct version, but the first one ( very very clean ) required that pybabel is already installed on the system.

In the second one ( this version ) we directly call pybabel command from setup.py instead of launching the bash script.


Now should work everything.

### Tests you can try:
##### virtualenv install
with a clean virtualenv ```python setup.py install```
##### virtualenv develop
with a clean virtualenv ```python setup.py develop```
##### pip install
with a clean virtualenv ```pip install libreant``` 
##### creating source dist package
rm -r dist build libreant.egg-info (clean cached stuff)
```python setup.py sdist```

**Comment by boyska** [comment]
actually, I created both sdist and bdist. But is not just the upload in pip that is wrong. If you try to do what I suggested in https://github.com/insomnia-lab/libreant/pull/56#issuecomment-70424113
for the current master, you'll see that it does not work.

That is, installing through the source distribution does not work.
Actually, the binary distribution *does* work.
If you do
```sh
python setup.py bdist_egg
easy_install dist/*.egg
```

you'll see that it works nicely.

Anyway, you're welcome in _removing_ the 0.1 release from pypi and doing another upload. I'm not confident that it will work, but let's try!

**Comment by ael-code** [comment]
> Anyway, you're welcome in removing the 0.1 release from pypi and doing another upload. I'm not confident that it will work, but let's try!

the current version on pypi it is based on this commit

**Comment by boyska** [comment]
And here's what happens when I run:
```sh
python setup.py sdist
wipeenv
pip install dist/libre*tar.gz
```
    Found link https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.9.tar.gz#md5=10a7c6bf81f91f280ba9e76e32e01c94 (from https://pypi.python.org/simple/markupsafe/), version: 0.9
  Using version 0.23 (newest of versions: 0.23, 0.22, 0.21, 0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.9.3, 0.9.2, 0.9.1, 0.9)
  Downloading MarkupSafe-0.23.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e (from https://pypi.python.org/simple/markupsafe/)
  Running setup.py (path:/home/gordo/.virtualenvs/libreant-pip/build/markupsafe/setup.py) egg_info for package markupsafe
    running egg_info
    creating pip-egg-info/MarkupSafe.egg-info
    writing pip-egg-info/MarkupSafe.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/MarkupSafe.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/MarkupSafe.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/MarkupSafe.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/MarkupSafe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/MarkupSafe.egg-info/SOURCES.txt'
  Source in /home/gordo/.virtualenvs/libreant-pip/build/markupsafe has version 0.23, which satisfies requirement markupsafe (from Jinja2>=2.5->Flask-Babel->libreant==0.1)
Installing collected packages: libreant, greenlet, Babel, speaklater, Jinja2, six, Werkzeug, itsdangerous, pytz, markupsafe
  Running setup.py install for libreant
    Running command /home/gordo/.virtualenvs/libreant-pip/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-SxMieC-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pzhRGV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gordo/.virtualenvs/libreant-pip/include/site/python2.7
    running install
    running build
    running compile_translations
    error: [Errno 2] No such file or directory
    Complete output from command /home/gordo/.virtualenvs/libreant-pip/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-SxMieC-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pzhRGV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gordo/.virtualenvs/libreant-pip/include/site/python2.7:
    running install

running build

running compile_translations

error: [Errno 2] No such file or directory

```

```

**Comment by boyska** [comment]
On Sun, Jan 18, 2015 at 02:26:10PM -0800, ael wrote:
>the current version on pypi it is based on this commit

and it does not work. Does it, for you? (I think we all should test the
things we do before claiming them :P)

-- 
boyska

**Comment by ael-code** [comment]
> and it does not work. Does it, for you? (I think we all should test the things we do before claiming them :P)

yes it works for me

**Comment by ael-code** [comment]
@boyska the version is the same but the package is changed. Could be possible that you are chaching the version 0.1?

**Comment by boyska** [comment]
To be sure, I manually downloaded https://pypi.python.org/packages/source/l/libreant/libreant-0.1.tar.gz#md5=a9cb8586bcd04cbbe912219d3513e2b7

then ran `pip install libreant*gz`
The error is always the same.

**Comment by ael-code** [comment]
manually downloaded and installed in a fresh env. All went fine. Also translations were compiled.

**Comment by frenko** [comment]
Try to install manually by download the source from https://pypi.python.org/packages/source/l/libreant/libreant-0.1.tar.gz#md5=a9cb8586bcd04cbbe912219d3513e2b7. The same error!!

**Comment by ael-code** [comment]
oke oke it's broken you are right

**Comment by boyska** [comment]
This is ok, but it doesn't solve the problem of depending on `babel` to be installed before libreant.

**Comment by boyska** [comment]
Sorry, didn't notice that you changed it. I'll test it now.

**Comment by boyska** [comment]
ok, it works, but won't create `.mo` files when babel is not installed. Even when babel is, it won't install them, because they're not recognized as `package_data`.

**Pull request merged**
