### PR TITLE
extend fsdb compatibility till v1.2.1

### PR DESCRIPTION
**Pull request by ael-code**

### CODE REVIEW

**Comment by boyska** [comment]
Haven't tested it, but reading the fsdb git log I wonder what about the `deep`/`depth` parameter: isn't that a breaking change?

**Comment by boyska** [comment]
well, since the travis test is actually picking the most recent available version (that is, 1.1) and everything seems to work, there's no need to work. Just answer the question, rebase, and merge it yourself.

**Comment by ael-code** [comment]
> Haven't tested it, but reading the fsdb git log I wonder what about the deep/depth parameter: isn't that a breaking change?

As stated in the changelog [0] this is not a breaking change.

[0] https://github.com/ael-code/pyFsdb/releases/tag/v1.2

**Comment by ael-code** [comment]
I will give you some days to test it by yourself. Then I'll merge it.

**Pull request merged**
