### PR TITLE
Elasticsearch2 upgrade docs

### PR DESCRIPTION
**Pull request by boyska**
`Installation` section upgraded (simplified!) to elasticsearch2. `Upgrading` section added.

### CODE REVIEW

**Comment by ael-code** [comment]
On 07/10/2016 03:56 PM, BoySka wrote:
> |Installation| section upgraded (simplified!) to elasticsearch2.
> |Upgrading| section added.

Since the upgrade procedure from version `0.4` will be still valid also
to move to other releases newer then the `0.5` I would use 'From 0.4'
instead of 'From 0.4 to 0.5'.

**Comment by boyska** [comment]
ael:
>On 07/10/2016 03:56 PM, BoySka wrote:
>> |Installation| section upgraded (simplified!) to elasticsearch2.
>> |Upgrading| section added.
>
>Since the upgrade procedure from version `0.4` will be still valid also
>to move to other releases newer then the `0.5` I would use 'From 0.4'
>instead of 'From 0.4 to 0.5'.

How can you know about it? :)

I'd say that we will clarify this things on the next release. Let's say,
if we later decide that upgrading from 0.4 to 0.6 in a single step is
impossible, we will say this, and describe the two steps separately. If
instead 0.5 and 0.6 will have same requirements, we will change it to
"From 0.4 to 0.5 or greater".

By now, "from 0.4 to 0.5" seems the clearest explanation to me.

**Comment by boyska** [comment]
As I was saying on #303 , I have some confusion about the python-elasticsearch library. In the doc, I'm saying "you just upgrade to 0.5, do nothing, everything works; still, we suggest you to upgrade with this procedure". Well, when we describe this procedure, shall I tell the user to install a new version of python-elasticsearch? Or, does the `1.x` version of python-elasticsearch supports both server versions?

**Comment by ael-code** [comment]
On 07/10/2016 04:44 PM, BoySka wrote:
> As I was saying on #303
> <https://github.com/insomnia-lab/libreant/pull/303> , I have some
> confusion about the python-elasticsearch library. In the doc, I'm saying
> "you just upgrade to 0.5, do nothing, everything works; still, we
> suggest you to upgrade with this procedure". Well, when we describe this
> procedure, shall I tell the user to install a new version of
> python-elasticsearch? Or, does the |1.x| version of python-elasticsearch
> supports both server versions?

As I've understood by the docs of python-elasticsearch and from what
I've experienced:

- python-elasticsearch `1.x` works with elasticsearch `1.x`
- python-elasticsearch `2.x` works with elasticsearch `2.x`


Thus, if we change the default supported elasticsearch version to `2.x`
we must upgrade also the python-elasticsearch deps to `2.x`.


According to me we should do this big change before the new libreant
release v0.5.

**Pull request merged**
