### PR TITLE
Users managment api

### PR DESCRIPTION
**Pull request by ael-code**
Here we are expanding REST API providing endpoint for users/groups/capabilities management.

This is very long and boring stuff but since I love you I've written tests that cover 100% of the new code ;)

I've decided to build an upper layer upon peewee: `users.api`. This layer expose higher api for managing users/groups/capabilities without requiring any knowledge of the database and peewee syntax.

### CODE REVIEW

**Comment by g3-3k** [comment]
it passes all test but I got ths warning:
No handlers could be found for logger "elasticsearch.trace"

**Comment by g3-3k** [comment]
How should I do to check whic user I am or what capabilities I have?
can you explain how to test this pull request?

**Comment by boyska** [comment]
>it passes all test but I got ths warning:
>No handlers could be found for logger "elasticsearch.trace"

this is not an issue

**Comment by ael-code** [comment]
> it passes all test but I got ths warning:
> No handlers could be found for logger "elasticsearch.trace"

This is completely normal. We don't register any logger for elasticsearch trace messages

> How should I do to check which user I am or what capabilities I have?
> can you explain how to test this pull request?

As I wrote in the PR description we are expanding API not implementing user login.

You can test as usual with `nosetests` command.

**Pull request closed without merging**
