### PR TITLE
preparing json deconding for new Flask version (1.0)

### PR DESCRIPTION
**Pull request by ael-code**
related to #247

### CODE REVIEW

**Comment by ael-code** [comment]
this is blocking PR #250

**Comment by boyska** [comment]
Ok, this is blocking, but is very difficult to test. There is no unit testing, and the API is not documented.

**Comment by ael-code** [comment]
On 03/06/2016 05:40 PM, BoySka wrote:
> Ok, this is blocking, but is very difficult to test. There is no unit
> testing, and the API is not documented.
> 

We already have unit test about this in `webant/test/api/test_api_users.py`.
For example  `test_add_user_wrong_content_type` and
`test_update_user_wrong_content_type`.


Anyway `request.json` is deprecated, so I switched to `get_json()`

About the comment:
`the next two lines should be removed when Flask version is >= 1.0`
is because on previous version of flask if the media-type was
unsupported instead of calling `on_json_load_error` it was returning
none. The code in this PR works on both old and new version of flask.

I read all the flask code of different version about json request,
they've changed a lot of stuff recently because the old code was a crap.

**Comment by boyska** [comment]
ael:
>BoySka wrote:
>> Ok, this is blocking, but is very difficult to test. There is no unit
>> testing, and the API is not documented.
>>
>
>We already have unit test about this in `webant/test/api/test_api_users.py`.

oh, you're right, that's my bad.

>Anyway `request.json` is deprecated, so I switched to `get_json()`

I see http://flask.pocoo.org/docs/0.10/api/#flask.Request.json

>I read all the flask code of different version about json request

that's why I love you

**Comment by leonaard** [comment]
i tested this, i will merge tomorrow if you dont have further comments

**Comment by boyska** [comment]
@ael-code should just rebase it, or github will complain. I agree with merging btw.

**Pull request merged**
