### PR TITLE
grant read capability to volumes to anonymous user by default

### PR DESCRIPTION
**Pull request by ael-code**
It seems that this is the most common scenario.

### CODE REVIEW

**Comment by boyska** [comment]
could you explain the change in the unit test?

**Comment by ael-code** [comment]
On 03/14/2016 01:47 AM, BoySka wrote:
> could you explain the change in the unit test?
> 

Before the change, by default,  there was only one capability
in the DB. So the capability with ID equal to 2 did not exist.
Now we've added another capability in the default setting, so
to test the delete operation on a non-existing capability, we need
to choose a number higher then 2.

**Comment by boyska** [comment]
ael:
>On 03/14/2016 01:47 AM, BoySka wrote:
>> could you explain the change in the unit test?
>>
>
>Before the change, by default,  there was only one capability
>in the DB. So the capability with ID equal to 2 did not exist.
>Now we've added another capability in the default setting, so
>to test the delete operation on a non-existing capability, we need
>to choose a number higher then 2.

got it, great

could you provide an integration test stating that providing a
not-yet-existent filename as `USERS_DATABASE` will result in anonymous
being authorized to view the volume page?

**Comment by ael-code** [comment]
On 03/14/2016 02:01 AM, BoySka wrote:
> ael:
>>On 03/14/2016 01:47 AM, BoySka wrote:
>>> could you explain the change in the unit test?
>>>
>>
>>Before the change, by default, there was only one capability
>>in the DB. So the capability with ID equal to 2 did not exist.
>>Now we've added another capability in the default setting, so
>>to test the delete operation on a non-existing capability, we need
>>to choose a number higher then 2.
> 
> got it, great
> 
> could you provide an integration test stating that providing a
> not-yet-existent filename as `USERS_DATABASE` will result in anonymous
> being authorized to view the volume page?
> 

This is a high level test. Should be placed in `webant/tests`. Could we
wait for #258?

**Comment by boyska** [comment]
ok

**Comment by ael-code** [comment]
Do we wanna merge?

**Pull request merged**
