### PR TITLE
compilation of translation using msgfmt

### PR DESCRIPTION
**Pull request by ael-code**
we do not need anymore pybabel/babel dependancy at build time. ;)

thanks to deluge guys and boyska.

I think that #57 will not be fixed by this. We need more testing.

If you test it, please explain the process step by step

### CODE REVIEW

**Comment by ael-code** [comment]
I found this.
http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/

I'll try.

**Comment by boyska** [comment]
well, the `package_data` part is actually not misleading to me. Anyway, that's how it is:
* MANIFEST controls the source distribution AND the binary one
* package_data only affects the binary one

Which means that `*.mo` should be in `package_data` without being in `MANIFEST.in`.

I also think that including `msgfmt.py` in MANIFEST.in is not needed, because every python file is automatically included... but who knows!

**Comment by boyska** [comment]
You forgot to `git add msgfmt.py`

**Comment by boyska** [comment]
I was wrong about removing msgfmt.py from `MANIFEST.in`

**Comment by ael-code** [comment]
> fuckity fuck to be funk

all seems to be fixed

**Comment by boyska** [comment]
Uff. Here, it does not seem to work: `.mo` files are created, but not included in binary distribution.
Have you removed temporary files? (I do that with `git clean -fdx`, but beware that non-checked-in files will be deleted!)

**Comment by ael-code** [comment]
oke oke simple to fix. Now Works. Works for me. ahahhahahahah.

**Comment by boyska** [comment]
so many stars! *_* ok, now it seems to work for me, too. Doing some odd test, just in case. Then I will merge.

my compliments for resisting to python packaging craziness!

**Pull request merged**
