### PR TITLE
documentation skeleton

### PR DESCRIPTION
**Pull request by boyska**
Adding a `doc/` directory which contains sphinx sources. It produces nice HTML in a way that is compatible with readthedocs.org

Indeed, you can have a preview at http://libreant.readthedocs.org/en/docs/index.html (that link is temporary: once it gets merged, `/en/latest` will take its place).

Merging this can start the documentation process.

Almost-useless bounty: it will also create [PDF](http://readthedocs.org/projects/libreant/downloads/pdf/docs/) and [EPUB](http://readthedocs.org/projects/libreant/downloads/epub/docs/)

To test that this works well, just do

```bash
pip install Sphinx
python setup.py build_sphinx
firefox build/sphinx/html/index.html
```

inside your virtualenv

### CODE REVIEW

**Comment by frenko** [comment]
If I use
```
python setup.py build_sphinx
```
I get this error:
``` sh
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_sphinx'
```

**Comment by boyska** [comment]
sorry, I missed to explain that you need to `pip install Sphinx`
@frenko can you try again?

**Comment by frenko** [comment]
Ok, now works, but compiled files are in ``build/sphinx/html`` and not in ``doc/build/html``

**Comment by boyska** [comment]
You are right; as that position is fine for me, I'm just changing the pull request documentation

**Comment by boyska** [comment]
mh, so, is there any other doubt or can this be merged?

**Comment by frenko** [comment]
sphinx should be added as a dependency of libreant?

**Comment by boyska** [comment]
mh, I don't think so: it's actually not needed to run libreant, just to build its documentation.

I've seen that most of the projects don't include sphinx in the dependencies, so I'd stick to this

**Comment by frenko** [comment]
Ok, that's right. For me we can merge it.

**Comment by boyska** [comment]
Don't be afraid of the green button :P

**Comment by boyska** [comment]
Great! Now we have up-to-date documentation on
http://libreant.readthedocs.org/en/latest/
(which automatically fetches the insomnia-lab/master branch)

In theory we also have one url for each release we do. But at the moment we have one release (v0.1) which still had no documentation support. In the future, everything should work.

**Pull request merged**
