### PR TITLE
[ docs ] add ubuntu installation procedure

### PR DESCRIPTION
**Pull request by ael-code**
debian installation procedure goes well also for ubuntu

### CODE REVIEW

**Comment by boyska** [comment]
I think that both for Debian and Ubuntu we should clarify on which version we tested it.

Ubuntu has quick releases, and debian is "near" to have a new version.

**Comment by ael-code** [comment]
> I think that both for Debian and Ubuntu we should clarify on which version we tested it.
> 
> Ubuntu has quick releases, and debian is "near" to have a new version.

Where will you put this note section?

**Comment by boyska** [comment]
Currently the title is Debian/Ubuntu. Instead, I'll something like `Debian Wheezy / Ubuntu Trusty / Whatever`

**Comment by ael-code** [comment]
I changed the commit. I've only added debian version beacuse I did not remember on which version of ubuntu the installation went fine.
I think we could merge this p.r and open an issue to remember to test installation on the latest ubuntu versions

**Pull request merged**
