### PR TITLE
Dependencies Update

### PR DESCRIPTION
**Pull request by ael-code**

### CODE REVIEW

**Comment by boyska** [comment]
could we add travis tests for versions that used to be up-to-date? If we want to assert that, for example, `Fsdb <= 1.2.2` is fine, then 1.1 should be tested. If we don't want to, then `Fsdb ==1.2` should be used.

I also don't appreciate much specifiying the patch release, unless it is really needed. Couldn't we just specifiy the major and minor, as per https://semver.org/ ?

**Comment by ael-code** [comment]
> I also don't appreciate much specifiying the patch release, unless it is really needed. Couldn't we just specifiy the major and minor, as per https://semver.org/ ?

Fixed

**Comment by ael-code** [comment]
@boyska wrote:
> could we add travis tests for versions that used to be up-to-date? If we want to assert that, for example, Fsdb <= 1.2.2 is fine, then 1.1 should be tested. If we don't want to, then Fsdb ==1.2 should be used.

I agree but I think it is better to wait for #321  since it will modify a little the test-matrix. I suggest to open an issue or wait for #321 to be merged

**Review by boyska — APPROVED** [review]
ok

**Pull request merged**
