### PR TITLE
[ templates ] search page stuff

### LINKED ISSUE #35: language on /search page
```language``` now is under key ```_language```. So language is not displayed.

### PR DESCRIPTION
**Pull request by ael-code**
- fixes #35
 - added navbar
 - added title

### CODE REVIEW

**Comment by boyska** [comment]
Yesterday @frenko learned how to test pull requests. Therefore I propose that frenko handles this pull request ;)

**Comment by boyska** [comment]
it seems to me that this pull request would also close #34 .

**Comment by frenko** [comment]
yeahhh. I've tested now. In the search results page I can't see infos about items, I only see the book image

**Comment by boyska** [comment]
mh, what exactly do you mean? I see like screenshot

**Comment by ael-code** [comment]
> it seems to me that this pull request would also close #34 .

Only the first point.

> yeahhh. I've tested it now. In the search results page I can't see infos about items, I only see the book image. I don't know if this is meant to be.

this thing happen since the very early commits of libreant. The search template assert that item have always title, actors and other optional field.
This branch do not try to fix this bug. Instead should fix #35.

I suggest you to test the changes introduced by commits of this branch and open an issue about the wrong assertion.

**Comment by boyska** [comment]
mh, I see that both points of #34 are solved by this. The screenshot is an example of this.

**Comment by ael-code** [comment]
I'll change #34, with a better explanation and without the first point.

**Comment by frenko** [comment]
In that page I see only book glipho and flag glipho with lang infos. I don't see anything else.
screenshot from 2015-01-16 17 17 40
I used ``git clone https://github.com/ael-code/libreant -b 35_search_page pr-41`` for test this pull req, it's a problem?

**Comment by boyska** [comment]
@frenko , maybe you just have no book with some title in your database. Please populate your database as suggested in [DATA.mdwn](https://github.com/insomnia-lab/libreant/blob/master/DATA.mdwn)

**Comment by frenko** [comment]
@boyska ok , all work well.

**Comment by ael-code** [comment]
> @boyska ok , all work well.

can we merge?

**Comment by frenko** [comment]
@ael-code yes, we can! ahahah

**Pull request merged**
