### PR TITLE
More web tests

### PR DESCRIPTION
**Pull request by boyska**
The web part is clearly undertested compared to other packages. This pull request is still far from a complete testing, but I don't want to wait that everything is tested, or I will just get lazy :)

The only important commit is `FIX unsafe handling of usersDB`. This fixes (partially) a problem related to the usage of globals in the users package.

### CODE REVIEW

**Comment by ael-code** [comment]
Two issue:
 - During tests it's not a good thing to use the default index.
 - `tearDown` method must be populated in order to destroy the test index created during the tests execution.

**Comment by boyska** [comment]
ael:
>Two issue:
> - During tests it's not a good thing to use the default index.
> - `tearDown` method must be populated in order to destroy the test index created during the tests execution.

can you be clearer about what part of the tests you are referring to?
it seems to me that what you ask is done.

**Comment by ael-code** [comment]
`webant/test/__init__.py`,  `webant/test/test_main_routes.py` and `webant/test/test_users_api.py`
 - the default indexname is used
 - in the tearDown function there is no index destruction

Remember that the index creation is triggered  also by a simply `GET /search`

I think that it should be useful to have a testCase subclass to be used as template for all the above cases.

Anyway what are the difference between tests in:
 - `webant/test/test_users_api.py` 
 -  `webant/test/api/test_api_users.py`

**Comment by boyska** [comment]
ael:
>Remember that the index creation is triggered  also by a simply `GET /search`

this makes the difference, now I see

>I think that it should be useful to have a testCase subclass to be used as template for all the above cases.

agree

>Anyway what are the difference between tests in:
> - `webant/test/test_users_api.py`
> -  `webant/test/api/test_api_users.py`

I think that I just haven't found those tests :) I will give a closer
look at those and discard anything that is not relevant

**Comment by ael-code** [comment]
I would like to merge this. Do you need something? Do you want me to submit a PR about the index leftover?

**Comment by boyska** [comment]
I'm sorry I'm a bit busy right now, so can't look at this. It was blocked on the comparison between those tests and the already existing ones, to be sure that those were not equal. So if you can do that, it would be much appreciated.

**Comment by ael-code** [comment]
Has been replaced by #278

**Pull request closed without merging**
