### PR TITLE
Users integration

### PR DESCRIPTION
**Pull request by ael-code**
We finally have login!!

### CODE REVIEW

**Comment by boyska** [comment]
the `libreant` command has a `--fsdb-path` and some `--es-*` options, but nothing like `--usersdb-path`.

So I run
```sh
LIBREANT_USERS_DATABASE='sqlite:////tmp/la.db' libreant -d     
```
which seems to work, but when I `GET /` gives a `authbone.authentication.AuthDataDecodingException` on `app.autht.perform_authentication()`

**Comment by ael-code** [comment]
On 11/05/2015 11:13 AM, BoySka wrote:
> the |libreant| command has a |--fsdb-path| and some |--es-*| options,
> but nothing like |--usersdb-path|.
> 
> So I run
> 
> LIBREANT_USERS_DATABASE='sqlite:////tmp/la.db' libreant -d     
> 
> which seems to work, but when I |GET /| gives a
> |authbone.authentication.AuthDataDecodingException| on
> |app.autht.perform_authentication()|
> 

This is really strange.
Can you provide the exec log and the output of `pip freeze`?

**Comment by boyska** [comment]
### pip freeze

```
Babel==2.1.1
click==5.1
dominate==2.1.16
elasticsearch==1.9.0
Flask==0.10.1
Flask-Authbone==0.1
Flask-Babel==0.9
Flask-Bootstrap==3.3.5.7
Flask-Script==2.0.5
Fsdb==0.3.3
gevent==1.1b6
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
libreant==0.2.1
MarkupSafe==0.23
opensearch==0.9.2
passlib==1.6.5
peewee==2.6.4
pytz==2015.7
speaklater==1.3
urllib3==1.12
visitor==0.1.2
Werkzeug==0.10.4
```

### log

```
2015-11-05 11:34:19,765 [archivant] [WARNING] It has not been set any value for FSDB_PATH, file operations will not be supported
Listening on http://0.0.0.0:5000/
2015-11-05 11:34:28,192 [webant] [ERROR] Exception on / [GET]
Traceback (most recent call last):
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/webant.py", line 93, in index
    return render_template('index.html')
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/index.html", line 3, in top-level template code
    {% import 'searchbar.html' as searchbar %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/index.html", line 11, in block "navbar"
    {{navbar.navbar(search=False)}}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/navbar.html", line 32, in template
    {% set user = current_user() %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/webant.py", line 245, in current_user
    app.autht.perform_authentication()
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Authbone-0.1-py2.7.egg/authbone/authentication.py", line 28, in perform_authentication
    raise AuthDataDecodingException()
AuthDataDecodingException
Traceback (most recent call last):
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 846, in handle_one_response
    self.run_application()
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/gevent-1.1b6-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 832, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/webant.py", line 279, in internal_server_error
    return renderErrorPage(message='Internal Server Error', httpCode=500)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/webant.py", line 289, in renderErrorPage
    return render_template('error.html', message=message, code=httpCode), httpCode
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/error.html", line 2, in top-level template code
    {% import "bootstrap/fixes.html" as fixes %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Bootstrap-3.3.5.7-py2.7.egg/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/error.html", line 10, in block "navbar"
    {{navbar.navbar(search=True)}}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/templates/navbar.html", line 32, in template
    {% set user = current_user() %}
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/libreant-0.2.1-py2.7.egg/webant/webant.py", line 245, in current_user
    app.autht.perform_authentication()
  File "/home/gordo/.virtualenvs/libreant-test/lib/python2.7/site-packages/Flask_Authbone-0.1-py2.7.egg/authbone/authentication.py", line 28, in perform_authentication
    raise AuthDataDecodingException()
AuthDataDecodingException
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'localhost:5000',
 'HTTP_USER_AGENT': 'curl/7.44.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '40252',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'dennis.ver.lan',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
 'werkzeug.request': None,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f5b7907a1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f5b70e8c738>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with AuthDataDecodingException

127.0.0.1 - - [2015-11-05 11:34:28] "GET / HTTP/1.1" 500 161 0.042243
```

**Comment by ael-code** [comment]
Oke, my fault :)

**Comment by ael-code** [comment]
On 11/05/2015 11:51 AM, ael wrote:
> Oke, my fault :)
> 

I forgot to release latest version of Flask-Authbone`.
You can now simply run
`pip install --upgrade --force flask-authbone`
and relaunch libreant.

**Comment by boyska** [comment]
ael wrote:
>I forgot to release latest version of Flask-Authbone`.
>You can now simply run
>`pip install --upgrade --force flask-authbone`
>and relaunch libreant.

well, I won't ;) if we are to require a minimum version of
flask-authbone, we'd better be explicit in setup.py

**Comment by boyska** [comment]
apart from the version thing, the code seems pretty good to me, and it apparently works.

**Comment by ael-code** [comment]
On 11/05/2015 02:42 PM, BoySka wrote:
> ael wrote:
>>I forgot to release latest version of Flask-Authbone`.
>>You can now simply run
>>`pip install --upgrade --force flask-authbone`
>>and relaunch libreant.
> 
> well, I won't ;) if we are to require a minimum version of
> flask-authbone, we'd better be explicit in setup.py
> 

minimum version constraints added for flask-authbone.

**Comment by boyska** [comment]
great! please rebase, or I cannot merge.

**Comment by ael-code** [comment]
> great! please rebase, or I cannot merge.

rebased

**Pull request merged**
