### PR TITLE
misc add volume improvements

### LINKED ISSUE #39: handle list insertion during item submission
see the following discussion for more info
https://github.com/insomnia-lab/libreant/pull/22#issuecomment-70121998

### PR DESCRIPTION
**Pull request by boyska**
yes, this is kinda all-mixed-in so consider this a request for opinions.
The first commit is really just moving code around so to look nicer
The second commit is about validating new volumes. Yes, this is done at the webant layer, which is probably not the best thing to do. Still, it cannot be done by `archivant` alone (archivant doesn't know about presets) and we still don't have an intermediate "controller" layer.

Last two commits add a new preset called "bag", which is basically a set (but "set" is a very ambigous word!). You may prefer to call it as a list. It has no real UI to handle lists (unless you call "just add `;` " an UI) but it works. I will *not* do the UI part of it until we have decided if duplicates are ok, which character is the separator, and this kind of stuff, because I would have to write more code, and because I'm lazy :) This would close #39

### CODE REVIEW

**Comment by ael-code** [comment]
> Last two commits add a new preset called "bag", which is basically a set (but "set" is a very ambigous word!). You may prefer to call it as a list. It has no real UI to handle lists (unless you call "just add ; " an UI) but it works. I will not do the UI part of it until we have decided if duplicates are ok, which character is the separator, and this kind of stuff, because I would have to write more code, and because I'm lazy :) This would close #39

I think that making the conversion from string to list into the validate step is not a good idea.
The preset validate function should receive a set, not a string.
According to me the conversion should be done on the client side.

**Comment by boyska** [comment]
I disagree with what you say, because there's no way to do so. Let's talk about numbers. We could have a "number" type. How do you expect the client to pass a number? there's only strings in http.

A lists could be json-serialized client-side, and then put into a string. But why is this any better than doing it server-side? It's an approach that can be applied to some specific types, but not to others.
For example, let's talk about a "date" object. Do you expect the client to pass a proper date object? and how?

I believe that the current solution is the only one that can make sense on the long term. Still, I really want to hear your opinion on this.

**Comment by boyska** [comment]
This seems to be stuck. Seems there are (too) many things in this PR, it might be better to split in several parts.
@ael-code what's your opinion on the first commits up to "webant validate volumes" ? this would postpone the discussion about the `list` type allowing for some progress

**Comment by ael-code** [comment]
For the second one: it seems that you've skipped to check if the `allow_upload` field of the preset is allowing to attach files.

The first one look good to me

**Comment by boyska** [comment]
ael:
>For the second one: it seems that you've skipped to check if the
>`allow_upload` field of the preset is allowing to attach files.

you're right

**Pull request closed without merging**
