### PR TITLE
Restore elasticsearch 2 compatibility

### PR DESCRIPTION
**Pull request by ael-code**
As discussed in #264 our code was not compatible with with newer version of ES.

This should fix the problem. 

I'm reporting the first commit message:

> this BREAKS compatibility with old already created index that were making
> use of the '_timestamp' field.
> 
> Unfortunatly the elasticsaerch guys have decided
> that we cannot use the put_mappings api to update the old index mapping
> to the new one:
> elastic/elasticsearch#13472
>

### CODE REVIEW

**Comment by boyska** [comment]
travis fails (and not _only_ because of `flake8`)!

also, we should provide an "upgrade path" for people that have an already running elasticsearch index and want to upgrade. (btw: usually software in the `0.x` phase does not care about this stuff. I care because there are "production" nodes of libreant. Which means that we should release libreant 1.0, no matter how many things we still need to do to be satisfied with it)

**Comment by ael-code** [comment]
> also, we should provide an "upgrade path" for people that have an already running elasticsearch index and want to upgrade. (btw: usually software in the 0.x phase does not care about this stuff. I care because there are "production" nodes of libreant. Which means that we should release libreant 1.0, no matter how many things we still need to do to be satisfied with it)


Since `put_mapping` api do not work (fuck !!!!) I think that the only way is to move all elements from the old index to a new one. This could be useful
https://www.elastic.co/blog/changing-mapping-with-zero-downtime


Anyway we need to test this PR against multiple elasticsearch version

**Comment by boyska** [comment]
Actually, that link says that adding a new field (like `insertion_date`) is ok. So if the index is already existent, and it has the `_timestamp` field, we can just add `insertion_date` and everything should be fine. Am I wrong on this?

**Comment by ael-code** [comment]
As I said, we can't. There is a discussion about that.
https://github.com/elastic/elasticsearch/issues/13472

If I well understood, if you have `_timestamp` already defined in the mapping of your type due to the bug, every subsequent `PUT maspping` request must include the `_timestamp` field.

I think that is better to introduce the breaking change at this point. Since libreant is not so popular yet.

**Comment by boyska** [comment]
ael:
>If I well understood, if you have `_timestamp` already defined in the mapping of your type due to the bug, every subsequent `PUT maspping` request must include the `_timestamp` field.

ok, what's the problem with this? we can add it again if it is already
present

>I think that is better to introduce the breaking change at this point. Since libreant is not so popular yet.

breaking changes are not a problem. The problem is that if we want to
set a breaking change we also need a way to upgrade from the previous
db.

**Comment by boyska** [comment]
To work on this, I'd like to have some easy way of testing migrations from ES1 to ES2. Testing things from ES1 or from ES2 is easy, but what about a migration? how do you do that? I'm considering doing things in a cointainer, sth like
* start from a container with ES1.7
* populate the db with some data
* use libreant
* upgrade to ES2.0
* run libreant and see what happens

Have you already done something like this? In case, please give me some detail/script/whatever.
Otherwise, I propose myself to work on this

**Comment by ael-code** [comment]
On 03/16/2016 04:00 PM, BoySka wrote:
> To work on this, I'd like to have some easy way of testing migrations
> from ES1 to ES2. Testing things from ES1 or from ES2 is easy, but what
> about a migration? how do you do that? I'm considering doing things in a
> cointainer, sth like
> 
>   * start from a container with ES1.7
>   * populate the db with some data
>   * use libreant
>   * upgrade to ES2.0
>   * run libreant and see what happens
> 
> Have you already done something like this? In case, please give me some
> detail/script/whatever.
> Otherwise, I propose myself to work on this
> 

I did not use any script for this. Proposal accepted :)

**Comment by boyska** [comment]
ael:
> BoySka wrote:
>> To work on this, I'd like to have some easy way of testing migrations
>> from ES1 to ES2. Testing things from ES1 or from ES2 is easy, but what
>> about a migration? how do you do that? I'm considering doing things in a
>> cointainer, sth like
>
>I did not use any script for this. Proposal accepted :)

have you done that manually? have you not tested migrations at all? :)

**Comment by ael-code** [comment]
On 03/16/2016 04:07 PM, BoySka wrote:
> ael:
>> BoySka wrote:
>>> To work on this, I'd like to have some easy way of testing migrations
>>> from ES1 to ES2. Testing things from ES1 or from ES2 is easy, but what
>>> about a migration? how do you do that? I'm considering doing things in a
>>> cointainer, sth like
>>
>>I did not use any script for this. Proposal accepted :)
> 
> have you done that manually? have you not tested migrations at all? :)


I didn't test the migration at all

**Comment by ael-code** [comment]
Do not consider to merge this PR. I'm working on it.

**Comment by ael-code** [comment]
This will continue on #281

**Pull request closed without merging**
