### PR TITLE
File infos

### PR DESCRIPTION
**Pull request by ael-code**
initial commits for implementing ```most downloaded``` section #15 :

 - updated file infos.   100e9a7
 - track downlaod files count

### CODE REVIEW

**Comment by boyska** [comment]
commit 7c56e46 (track download files count) "needs" commit cb66a13 (added function to increment file download count) to work. The order should be inverted.

**Comment by ael-code** [comment]
you must not trust the pull request interface order. The commit tree was correct:
```
100e9a7 indipendence from fsdb and file download count
13d994c [ dbapi ] added function to increment file download count efficiently
93c3c0e track downlaod files count
```

**Comment by boyska** [comment]
ahahah, ok sorry for this :)
The only problem is that this is "hard" to count, since download count is stored but not shown. Maybe merging the json thing before this will make it easier to test?

**Comment by ael-code** [comment]
> The only problem is that this is "hard" to count, since download count is stored but not shown.

What do you mean?

to test it I used [json_response branch](https://github.com/ael-code/libreant/tree/json_response).

That branch will become a pull request as soon as #32 will be merged. I need to rebase upon it.

Use can use also the es way:
```curl "localhost:9200/book/book/<bookid>?pretty=true"```

**Comment by boyska** [comment]
To test this branch, I also need to test another one. But ok, no problem, just wait for #32  to be merged, then we will merge the `json_response`, then this can be tested and merged.

**Comment by ael-code** [comment]
I probably would not have explained well.

This branch and #32 are completely independent.

It's easy to test if counter are working:
 - insert an item with a file through the web interface
 - get the id of the new item
 - try to download the file uploaded with the new item for n times
 - use curl to retrieve all item metadata:

    ```curl "localhost:9200/book/book/<item_id>?pretty=true"```
 - check if ```download_count``` field is equal to n

So there is no reason to wait for #32 

Sorry for my bad English. I can imagine how difficult it is to understand me

**Comment by boyska** [comment]
Ok, got it. There is one minor bug. If I click on the download button, but then press "cancel" on firefox (that is, I start to download but never finish to) the download is counted anyway. I don't know if and how this can be solved. Maybe something about passing the file with `yield`, but I don't really know

**Comment by ael-code** [comment]
> Ok, got it. There is one minor bug. If I click on the download button, but then press "cancel" on firefox (that is, I start to download but never finish to) the download is counted anyway. I don't know if and how this can be solved. Maybe something about passing the file with yield, but I don't really know

I knew this behavior. I think this is a very minor issue that will require a lot of efforts. I decided to ignore it for now.

**Comment by boyska** [comment]
Ok, so I'll merge it; but please open an issue about this minor thing.

**Pull request merged**
