### PR TITLE
Users

### PR DESCRIPTION
**Pull request by ael-code**
This is the working prototype code for users managment.

All the *accrocco* is managed by [peewee](http://peewee.readthedocs.org/en/latest/) a simple and small SQL ORM and [passlib](http://pythonhosted.org/passlib) to manage passwords
We have 3 main element:
 - User
 - Group
 - Capability

You can look at the docs for specific details. 
Anyway users could belong to one or more groups and every group has a set of capabilities.
A **capability** is composed by a domain and an action. It represent the possibility to perform a specific set of actions on the resources described by the domain. The domain is represent by a regular expression and action by a bitmask.

I wrote a lot of new tests that cover the 100% of the new package. I've also tried to document users code.

I'm making this code available to you in order to decide together if it's could be a good base to work on.

### CODE REVIEW

**Comment by ael-code** [comment]
> this is not an "encryption", but a key derivation (or key stretching). Well, ok, just a matter of words

Completely right!

> I'm not really sure that hashed sha1 is a good key derivation function. https://docs.python.org/2.7/library/hashlib.html#hashlib.pbkdf2_hmac surely is, instead

Let's fire up ours CPUs

Both 1 and 2 fixed in 4539411f594e1d408e4a9fd36fb9052c91fb6d48

**Comment by ael-code** [comment]
> If I understand this correctly, some operations (which are very common) are "hardcoded", and is assumed that the same set of capabilities make sense for every domain (which is ok: if a capability makes no sense in some domain, just don't use it). When at some point a new capability (for example an "admin" operation, or a "send to other peer") is needed, what should I do? I guess that just putting ADMIN = 2**4 somewhere is fine, and then obviously I should be sure that no two capabilities are using the same numbers.

The actual capability system (domain+action) is well suited for **all** operations that in some way effects our DB, in fact I've followed the CRUD paradigm.
For all operation that do not follow (domain+action) pattern we could use the domain field for string description and set action field to a dummy value.
 
> 
> This is not really bad, but... can't we just use strings for it? (Yes, I suppose this is because of efficiency reasons. damn them :P)
>

This is not only for efficiency reasons, if we use strings also for action field, we need to create and follow a standard for the action string format.
Bitmask keep comparision and conversion simple but maintain an high grade of flexibility (is relatively easy to add new operations)

> Just to be clear: I am not really convinced of what I am saying. I just want to understand better.

**Comment by boyska** [comment]
On Tue, Sep 29, 2015 at 08:02:24AM -0700, ael wrote:
>> If I understand this correctly, some operations (which are very common) are "hardcoded", and is assumed that the same set of capabilities make sense for every domain (which is ok: if a capability makes no sense in some domain, just don't use it). When at some point a new capability (for example an "admin" operation, or a "send to other peer") is needed, what should I do? I guess that just putting ADMIN = 2**4 somewhere is fine, and then obviously I should be sure that no two capabilities are using the same numbers.
>
>The actual capability system (domain+action) is well suited for **all** operations that in some way effects our DB, in fact I've followed the CRUD paradigm.
>For all operation that do not follow (domain+action) pattern we could use the domain field for string description and set action field to a dummy value.

ok, so I took it wrong. Now I understand. Thanks, this is perfectly
reasonable.

-- 
boyska

**Comment by ael-code** [comment]
> that's what a digest like that in https://pythonhosted.org/passlib/lib/passlib.hash.pbkdf2_digest.html is for. Realistically, I see only one case: a server deciding to lower count for performance reasons (or to increase it after a paranoia attack)
Yes, it would be one more dependency.

I was impressed about the increase of test time requirments after we've moved to pbkdf2, 
keeping in mind that and the nature of this project (chip/old hardware support), I think that provide possibility to change parameters that heavily affect performance (like stretching rounds) would be crucial.

I'll move to passlib soon.

**Comment by ael-code** [comment]
> I'll move to passlib soon.

The new commits now use passlib for password managment.
Users package has introduced 3 new configuration variable:
```python
'USERS_DATABASE': ("sqlite:////tmp/libreant_users.db", "url of the database used for users managment"),
'PWD_SALT_SIZE': (16, "size of the salt used by password hashing algorithm"),
'PWD_ROUND_SIZE': (2900, "number of rounds runs by password hashing algorithm")
```

**Comment by boyska** [comment]
>```
>'PWD_ROUND_SIZE': (2900
>```

Is there any reason for such a number? Why not 2000 or 3000? And most of
all, why not follow `PasswordHash.default_rounds` (which is much
higher!)?

**Comment by ael-code** [comment]
On 10/01/2015 09:50 AM, BoySka wrote:
>>```
>>'PWD_ROUND_SIZE': (2900
>>```
> 
> Is there any reason for such a number? Why not 2000 or 3000? And most of
> all, why not follow `PasswordHash.default_rounds` (which is much
> higher!)?
> 

Actually 2900 is the passlib standard, is hardcoded in [1]

[1]
https://bitbucket.org/ecollins/passlib/src/fa26802fc88fbc6b2d4b9676970bed7e6d53fc9d/passlib/handlers/pbkdf2.py?at=default&fileviewer=file-view-default#pbkdf2.py-137

**Comment by boyska** [comment]
>Actually 2900 is the passlib standard, is hardcoded in [1]

no, it's 29000 :D

still, explicitly getting the value from passlib would be better (if
possible) to delegate this kind of choices to "security-oriented"
parties.

**Comment by ael-code** [comment]
On 10/01/2015 05:19 PM, BoySka wrote:
>>Actually 2900 is the passlib standard, is hardcoded in [1]
> 
> no, it's 29000 :D

eheh ok

> 
> still, explicitly getting the value from passlib would be better (if
> possible) to delegate this kind of choices to "security-oriented"
> parties.
> 

fixed: now the value it's taken from passlib.
Anyway we need to remember to change the default rounds value if we'll
movde to `pbkdf2_sha512`.

**Comment by ael-code** [comment]
I've added a stupid bugfix with the latest commit

Do you need more time to check this pr or we could merge?

**Comment by boyska** [comment]
ael wrote:
>Do you need more time to check this pr or we could merge?

well, I have a proposal which changes the usual PR method: let's merge
it (since it's clearly an improvement over the current situation), but
maybe give me some time to see how it "feels" before basing too much
work on this. Is it ok for you?

**Comment by boyska** [comment]
Ok, now I read it all and I am fairly convinced, except for one thing. We always said that we should have supported multiple ways of getting authentication/authorization, especially referring to IP source or simlar other aspects. See #6 and #76 .

I suppose that this kind of thing will be done using `flask_authbone` (`users_cont` branch is probably what I need to understand better).

If you can reassure me about this, I will merge this PR immediately.

**Comment by ael-code** [comment]
On 10/04/2015 01:46 PM, BoySka wrote:
> Ok, now I read it all and I am fairly convinced, except for one thing.
> We always said that we should have supported multiple ways of getting
> authentication/authorization, especially referring to IP source or
> simlar other aspects. See #6
> <https://github.com/insomnia-lab/libreant/issues/6> and #76
> <https://github.com/insomnia-lab/libreant/issues/76> .
> 
> I suppose that this kind of thing will be done using |flask_authbone|
> (|users_cont| branch is probably what I need to understand better).
> 
> If you can reassure me about this, I will merge this PR immediately.
> 

`users_cont` contains only some experiments :). Anyway flask_authbone
will help us only in building decorators needed for
authentication/authorization.
Indeed we will have some group of users like (lan, internet
unauthenticated, etc...) that will not have their own specific user in
the SQL database.We could use the users api layer to link those
'virtual' users to the proper SQL groups in order to grep their permissions.

Anyway I think that this pr it's actually a good base for our needs, and
fits with 'virtual' users scenario.

**Pull request merged**
