### PR TITLE
Add Vagrantfile for setting up libreant

### PR DESCRIPTION
**Pull request by hellais**

### CODE REVIEW

**Comment by boyska** [comment]
Some prior notes:
* some form of checksum could be useful to avoid download errors. The option should be `config.vm.box_download_checksum`; see also http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html
* `/liberant` is a typo; it should have been `/libreant`

**Comment by boyska** [comment]
Also: elasticsearch should be automatically started. This can be done with
`update-rc.d elasticsearch defaults`

**Comment by hellais** [comment]
Should now be fixed.

**Comment by boyska** [comment]
Mh, there is still some problem, but we are getting near!

The `update-rc.d` thing work great; unfortuanetely, the first "vagrant up" that you do will not be followed by a reboot. So there should be a `service elasticsearch start`, too.

Also, it would be great if the script is idempotent. This would allow us to re-run `vagrant provision` when it changes. This is some tweak that you might like to implement:
* appending to `sources.list` will cause noises.  `echo deb "htppblablab" > /etc/apt/sources.list.d/elasticsearch.list` would be better
* more explicitly asking python2.7 would be better; both in package lists and in virtualenv `-p` option argument
* `export DEBIAN_FRONTEND=noninteractive` would be good, too

Last doubt: I don't like very much that the virtualenv is inside the synced folder. Wouldn't it be better to just put it on `/ve`? This has three advantages:
1. not pollute the working directory
2. if you have more than one box, the names does not conflict
3. it's shorter to type `/ve/bin/webant` than `/libreant/ve-precise32/bin/webant`! (ok, that's minor)

Sorry for so many issues raised, I think that this is great and we're quite near to a merge :)

**Comment by boyska** [comment]
perfect, merging!

**Pull request merged**
