### PR TITLE
Various logs fixes

### PR DESCRIPTION
**Pull request by ael-code**
Various small fixes. Look at the commit history for more details.

Keep in mind that we will move soon to a more robust way for logging configuration

### CODE REVIEW

**Comment by boyska** [comment]
At a first glance, everything seems fine. Could you explain the "pin security" thing?

**Comment by ael-code** [comment]
> At a first glance, everything seems fine. Could you explain the "pin security" thing?

I don't know what it is :) , it was introduced in the newer version of werkzeug. Since It produces 2 additional lines of code and we are not going to use it, I decided to remove it.

**Comment by ael-code** [comment]
I would like to merge this and release the `0.3` version.

**Comment by boyska** [comment]
I will test **NOW**

**Comment by boyska** [comment]
It does not work. 

```
TypeError: __init__() got an unexpected keyword argument 'pin_security'
```

I think this is because you are using a more recent flask version than I am (I'm using `Flask==0.10.1`). Please _resist_ the urge to force to require a very recent version of flask, or I'll need to create an infinite number of debian packages (see #229 and https://packages.debian.org/jessie/python-flask ).

Apart from this, I can't see what's the improvement of this PR. I don't think this is needed to release 0.3.

**Comment by ael-code** [comment]
> Apart from this, I can't see what's the improvement of this PR. I don't think this is needed to release 0.3.

Ok. I've assigned this the next release.

**Comment by ael-code** [comment]
Ok, debugger pin is now [documented](http://werkzeug.pocoo.org/docs/0.11/debug/#debugger-pin) and seems a nice feature. I've reverted 1fc91bb.

I also modified travis conf to make it run tests with different version of gevent  [`1.0.1`, `1.0.2`, `1.1rc5`].

**Comment by boyska** [comment]
I am trying to review this PR.

First of all, I'd like a description on the clear advantages of this. I see some refactoring, and they seem good and I am wililng to merge them. But if there is any behavior change I'd like it to be described. I guess that the logging is somewhat "better", but could you be clearer about this?

Secondly, the `pin_debugger` takes two commits: one does something, the other reverts it. Can you please remove both so that the history is cleaner and shorter?

**Comment by boyska** [comment]
Small note (this is more of a reminder to my self than a comment to the actual code): the way you forced the gevent is not entirely correct. It works, but only because in `setup.py` we do not specify a version. If we were to specify a version in setup.py (as I am proposing in #254 ) that would not work. The fix is trivial: use `before_script` instead of `before_install`, as I did in #256 .

**Comment by ael-code** [comment]
> First of all, I'd like a description on the clear advantages of this. I see some refactoring, and they seem good and I am wililng to merge them. But if there is any behavior change I'd like it to be described. I guess that the logging is somewhat "better", but could you be clearer about this?

Now all the output of libreant is handled in the python-logger way this is translated in:
 - we have now an homogeneous logging
 - we could control all the loggings from a single place

### Logging examples:

#### Previous logging
```
2016-03-04 04:44:47,150 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH": null}
2016-03-04 04:44:47,151 [archivant] [WARNING] It has not been set any value for FSDB_PATH, file operations will not be supported
2016-03-04 04:44:47,151 [webant] [WARNING] It has not been set any value for 'USERS_DATABASE', all operations about users will be unsupported. Are all admins.
 * Restarting with stat
2016-03-04 04:44:47,513 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH": null}
2016-03-04 04:44:47,513 [archivant] [WARNING] It has not been set any value for FSDB_PATH, file operations will not be supported
2016-03-04 04:44:47,514 [webant] [WARNING] It has not been set any value for 'USERS_DATABASE', all operations about users will be unsupported. Are all admins.
 * Debugger is active!
 * Debugger pin code: 103-075-757
Listening on http://0.0.0.0:5000/
2016-03-04 04:44:51,234 [libreantdb.api] [DEBUG] waiting for index "libreant" to be ready
2016-03-04 04:44:51,240 [libreantdb.api] [DEBUG] index "libreant" is now ready
10.10.2.2 - - [2016-03-04 04:44:51] "GET /search?q=%2A%3A%2A HTTP/1.1" 200 11850 0.109837
10.10.2.2 - - [2016-03-04 04:44:51] "GET /static/bootstrap/css/bootstrap.min.css?bootstrap=3.3.5.7 HTTP/1.1" 304 191 0.006109
10.10.2.2 - - [2016-03-04 04:44:51] "GET /static/item_list.css HTTP/1.1" 304 188 0.001848
10.10.2.2 - - [2016-03-04 04:44:51] "GET /static/bootstrap/jquery.min.js?bootstrap=3.3.5.7 HTTP/1.1" 304 190 0.001773
10.10.2.2 - - [2016-03-04 04:44:51] "GET /static/bootstrap/js/bootstrap.min.js?bootstrap=3.3.5.7 HTTP/1.1" 304 190 0.003595
10.10.2.2 - - [2016-03-04 04:44:51] "GET /static/js/ui-main.js HTTP/1.1" 304 187 0.001538
```

#### Homogeneous logging
```
2016-03-04 04:40:58,608 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH": null}
2016-03-04 04:40:58,609 [archivant] [WARNING] It has not been set any value for FSDB_PATH, file operations will not be supported
2016-03-04 04:40:58,609 [webant] [WARNING] It has not been set any value for 'USERS_DATABASE', all operations about users will be unsupported. Are all admins.
2016-03-04 04:40:58,630 [werkzeug] [INFO]  * Restarting with stat
2016-03-04 04:40:58,956 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH": null}
2016-03-04 04:40:58,957 [archivant] [WARNING] It has not been set any value for FSDB_PATH, file operations will not be supported
2016-03-04 04:40:58,957 [webant] [WARNING] It has not been set any value for 'USERS_DATABASE', all operations about users will be unsupported. Are all admins.
2016-03-04 04:40:58,976 [werkzeug] [WARNING]  * Debugger is active!
2016-03-04 04:40:58,977 [werkzeug] [INFO]  * Debugger pin code: 103-075-757
2016-03-04 04:40:58,991 [webant] [INFO] Listening on http://0.0.0.0:5000/
2016-03-04 04:43:47,381 [libreantdb.api] [DEBUG] waiting for index "libreant" to be ready
2016-03-04 04:43:47,396 [libreantdb.api] [DEBUG] index "libreant" is now ready
2016-03-04 04:43:47,551 [webant] [INFO] 10.10.2.2 - - [2016-03-04 04:43:47] "GET /search?q=%2A%3A%2A HTTP/1.1" 200 11850 0.235244
2016-03-04 04:43:47,576 [webant] [INFO] 10.10.2.2 - - [2016-03-04 04:43:47] "GET /static/item_list.css HTTP/1.1" 304 188 0.004779
2016-03-04 04:43:47,578 [webant] [INFO] 10.10.2.2 - - [2016-03-04 04:43:47] "GET /static/js/ui-main.js HTTP/1.1" 304 187 0.000851
```

Of course if you don't have gevent >= 1.1 requests logging will be in the old not-homogeneous format. But this is discovered at runtime in a transparent way.

**Comment by boyska** [comment]
ael:
>> First of all, I'd like a description on the clear advantages of this. I see some refactoring, and they seem good and I am wililng to merge them. But if there is any behavior change I'd like it to be described. I guess that the logging is somewhat "better", but could you be clearer about this?
>
>Now all the output of libreant is handled in the python-logger way this is translated in:
> - we have now an homogeneous logging
> - we could control all the loggings from a single place

Now I see. Ok, I will test those things asap so that I can merge
everything.

-- 
boyska

**Comment by ael-code** [comment]
#### Commit history cleaned:

> Secondly, the pin_debugger takes two commits: one does something, the other reverts it. Can you please remove both so that the history is cleaner and shorter?

I've removed both the commit related to pin-debugger. If pin-debugger functionality is available well use it

#### Gevent 1.1.0 release

As stated in #259, gevent 1.1.0 as been released. In order to support the new version I did:
 - fix gevent supported version in `setup.py`  ->  [`1.0.1`, `1.1.0`]
 - make travis-ci try to install all the stable versions in the supported range: `1.0.1`, `1.0.2`, `1.1.0` 

#### Prayer :pray: 
Please consider merging this, it has been submitted on `Dec 11, 2015` and makes our logs so sexy.

**Comment by boyska** [comment]
ael:
>#### Commit history cleaned:
>
>> Secondly, the pin_debugger takes two commits: one does something, the other reverts it. Can you please remove both so that the history is cleaner and shorter?
>
>I've removed both the commit related to pin-debugger. If pin-debugger functionality is available well use it
>
>#### Gevent 1.1.0 release
>
>As stated in #259, gevent 1.1.0 as been released. In order to support the new version I did:
> - fix gevent supported version in `setup.py`  ->  [`1.0.1`, `1.1.0`]
> - make travis-ci try to install all the stable versions in the supported range: `1.0.1`, `1.0.2`, `1.1.0`

But is this useful at all? What I mean is that the code related to
gevent is never run during tests, so I don't think it will be useful to
do all the unit tests with different gevent version

>#### Prayer :pray:
>Please consider merging this, it has been submitted on `Dec 11, 2015` and makes our logs so sexy.

ok

**Comment by ael-code** [comment]
> But is this useful at all? What I mean is that the code related to gevent is never run during tests, so I don't think it will be useful to do all the unit tests with different gevent version

Yeap I know. I hope we'll be able to test it in the near future

**Pull request merged**
