### PR TITLE
shut up, flake8

### PR DESCRIPTION
**Pull request by boyska**
I don't know how that code sneaked into the repository, but this commit fixes that

### CODE REVIEW

**Comment by ael-code** [comment]
I did not managed to handerstand these changes. Can you provide some additional explanation?

**Comment by boyska** [comment]
>I did not managed to handerstand these changes. Can you provide some additional explanation?

sure.
flake8 complains when the `import` are not at "top-level". Which means
that if there is "code" between the import, it will complain and travis
will fail.

In one case (logging in agherant) I just moved it later.
In another I used the "noqa" feature of flake8: when you use "noqa" as a
line comment, you are disabling any check for _that_ line.

**Comment by ael-code** [comment]
On 02/05/2016 03:24 PM, BoySka wrote:
>>I did not managed to handerstand these changes. Can you provide some
> additional explanation?
> 
> sure.
> flake8 complains when the `import` are not at "top-level". Which means
> that if there is "code" between the import, it will complain and travis
> will fail.
> 

There were no problems since now with those lines and flake8 tests. What
is changed? Is it something about flake8 update?

> In one case (logging in agherant) I just moved it later.
> In another I used the "noqa" feature of flake8: when you use "noqa" as a
> line comment, you are disabling any check for _that_ line.
>

**Comment by boyska** [comment]
ael wrote:
BoySka wrote:
>> flake8 complains when the `import` are not at "top-level". Which means
>> that if there is "code" between the import, it will complain and travis
>> will fail.
>>
>
>There were no problems since now with those lines and flake8 tests. What
>is changed? Is it something about flake8 update?

I don't know, so yes, I believe a flake8 update. But without this
commit, any PR is going to fail.

**Pull request merged**
