### PR TITLE
Added language documentation (localization)

### PR DESCRIPTION
**Pull request by leophys**
Added a very simple page to describe (and encourage) the translation process of the web interface.

### CODE REVIEW

**Comment by boyska** [comment]
@leophys great.
But you should rebase on the current insomnia-lab master. Look at the commit list above. You are asking us to merge things about agherant!

```sh
git checkout -b 83-translators-documentation
git rebase -i insomnia-lab/master
```

and choose the commit that you need to pick.

**Comment by boyska** [comment]
Why is it _under_ the API in the toctree? I find it a strange place. I think that a good place is between sysadmin and developer.

**Comment by boyska** [comment]
The explanation is not very clear to me. It is said that I should edit the `webant/translations/en/LC_MESSAGES/messages.po`. I'm not sure that it is completely correct, and I'll be glad to listen @ael-code in this respect, but ok. If I don't like github, I should send a mail and get a file back. Why don't we just link that file to download from github using just a browser? Here is the link: https://raw.githubusercontent.com/insomnia-lab/libreant/master/webant/translations/en/LC_MESSAGES/messages.po
By the way, what if the language I can translate _already_ has his own `messages.po` file, but is incomplete? Downloading the english one I am just throwing everything away.

Then I should open the `*.po files` (why an asterisk? wasn't it always `messages.po`? and why the plural? wasn't it a single file?) and I should save it. Then, a note says that I should create a directory and put the file *there*. I think that it is rather difficult to follow this workflow, maybe doing the opposite would be easier.

**Comment by leophys** [comment]
@boyska regarding the workflow, in my opinion it is simpler for people who are not confident with git and github to receive the ``messages.po`` file from us. If one contacts us, announcing that he can translate the interface in a certain language, we look if such a translation exists (and is incomplete) or not. At that point the translator will receive a file. Either complete (coming from ``webant/translations/<lang>/LC_MESSAGES/messages.po``) or a blank one (coming from ``webant/translations/en/LC_MESSAGES/messages.po``).
Once finished the translator can send the file back to us and we can include it in the right path.
In this sense, it is better to let us control which file to give to the translator.

About the last point, I'm not confident that the only possible file used by Flask-Babel in general is called ``messages.po``. I should rtfm a bit :)

Proceeding to improve the pull request.

**Comment by boyska** [comment]
Ok, that's a very good point for non-tech people. About `messages.po`, I'm not that sure either. Still want to hear @ael-code about this :)
But what about people comfortable with github? you told them to take the one from `en/` directory, then copy it in the other directory, which maybe is not what they want.

**Comment by ael-code** [comment]
> Either complete (coming from webant/translations/<lang>/LC_MESSAGES/messages.po) or a blank one (coming from webant/translations/en/LC_MESSAGES/messages.po).

Seems correct to me. Indeed the the correct procedure in case of new language should be to initialize a new messages catalog for that language and then give this to the translator. But I think that also the @leophys way should works.

>Ok, that's a very good point for non-tech people. About messages.po, I'm not that sure either. Still want to hear @ael-code about this :)

I didn't get the question. Sorry :)

**Comment by boyska** [comment]
>I didn't get the question. Sorry :)

the exact question is: is the file always called `messages.po`? Is it
possible that more than one file exists?

Being sure that it's always just one, and always with the same name,
would help in making simpler instructions.

**Comment by ael-code** [comment]
> the exact question is: is the file always called `messages.po`? Is it possible that more than one file exists?

according to [babel docs](http://babel.pocoo.org/docs/setup/#options) the domain could change, so the name too.

**Comment by boyska** [comment]
The domain could change, but, if i understand it correctly, the choice is up to us. So if we stick to "messages", we can make a simpler documentation. What do you think?

**Comment by ael-code** [comment]
> The domain could change, but, if i understand it correctly, the choice is up to us. So if we stick to "messages", we can make a simpler documentation. What do you think?

Surely... we can stick to "message".

**Comment by boyska** [comment]
ok @leophys , so:
> I'm not confident that the only possible file used by Flask-Babel in general is called messages.po. 

You can now assume that the file will always be called `messages.po`.

**Comment by leophys** [comment]
Preparing new pull request. Closing without merging.

**Pull request closed without merging**
