### PR TITLE
Add book ( revisioned )

### PR DESCRIPTION
**Pull request by ael-code**
This branch is almost the same of #9 but has a more clean commits tree

Implemented system to upload items to libreant, general restyling

I have tried to implement all functionality introduced by @frenko on his [fork](https://github.com/frenko/libreant/). @frenko you should check if I am missing something.

#### New route:
 - /add ( POST | GET )
 - /download/{bookid}/{fileid}

#### New pip dependecies:
 - Fsdb ;)

#### Open points:
 ( to be converted into issues )
 - how to handle Fsdb path
 - how to display book info and related download
 - how to handle list insertion during item submission

#### Screens:

libreant_add

libreant_index

### CODE REVIEW

**Comment by boyska** [comment]
so what should we do with #9 ? has it to be discarded?

**Comment by ael-code** [comment]
Yes.

**Comment by boyska** [comment]
This is not "automatically mergeable" anymore.
I know, I could rebase it myself, but you'll probably be quicker. So please do :P

**Comment by ael-code** [comment]
I've done the rebase. 
I removed the split function from ```PRESET_PATHS```

Seems that all is working.

**Comment by boyska** [comment]
There is a problem with list fields, I suppose. For example, `actors` was intended to be a list field, but there's no way to do it. Doing so results in 
screenshot

(in the view, actors is treated as a list, which does not make sense).

I know that we are wondering about the best solution to this issue, but was just in order to review

**Comment by ael-code** [comment]
> There is a problem with list fields, I suppose. For example, actors was intended to be a list field, but there's no way to do it

this is included in the open points.
The problem will verify for all the list fields. We need to found a global and consistent solution.
Anyway open points of this pull request will become issues as soon as this branch will be merged.

**Comment by boyska** [comment]
It seems to me that everything is properly working. I also tried to add a duplicate image, and fsdb handles that perfectly (as expected, thanks to sha1sum as path). merging.

**Comment by boyska** [comment]
this closes #5

**Pull request merged**
