### PR TITLE
block flask version to 0.10

### PR DESCRIPTION
**Pull request by boyska**
**HEAVY TESTING: don't even consider this for merging**

(I am doing tests on travis, so creating a PR is the easiest thing)

refs #254

### CODE REVIEW

**Comment by ael-code** [comment]
On 03/03/2016 07:47 PM, BoySka wrote:
> /HEAVY TESTING: don't even consider this for merging/
> 
> (I am doing tests on travis, so creating a PR is the easiest thing)
> 
> refs #254 <https://github.com/insomnia-lab/libreant/issues/254>
> 

You can also enable Travis-ci on your branches.

**Comment by boyska** [comment]
ael:
>On 03/03/2016 07:47 PM, BoySka wrote:
>> (I am doing tests on travis, so creating a PR is the easiest thing)
>
>You can also enable Travis-ci on your branches.

you're right :) now I did!

**Comment by ael-code** [comment]
On 03/04/2016 04:24 PM, BoySka wrote:
> ael:
>>On 03/03/2016 07:47 PM, BoySka wrote:
>>> (I am doing tests on travis, so creating a PR is the easiest thing)
>>
>>You can also enable Travis-ci on your branches.
> 
> you're right :) now I did!

Can we close this PR now?

**Comment by boyska** [comment]
ok

**Pull request closed without merging**
