### PR TITLE
changelog for version 0.5

### PR DESCRIPTION
**Pull request by ael-code**
:warning:  Be aware that this wont be merged on `dev` branch.

We need to write also something about the migration to elasticsearch 2. How do we wanna proceed?

### CODE REVIEW

**Comment by boyska** [comment]
I think that the first step is recalling what does the new code do. Now, libreant
* still supports elasticsearch1
* supports elasticsearch2 for new instances
* if you upgrade from elasticsearch1 to elasticsearch2, this will require a manual upgrade procedure. (We should probably document this)

**Comment by ael-code** [comment]
On 07/10/2016 03:05 PM, BoySka wrote:
> I think that the first step is recalling what does the new code do. Now,
> libreant
> 
>   * still supports elasticsearch1
>   * supports elasticsearch2 for new instances
>   * if you upgrade from elasticsearch1 to elasticsearch2, this will
>     require a manual upgrade procedure. (We should probably document this)
> 

Where do you think it is better to put the upgrade procedure documentation?

**Comment by boyska** [comment]
Inside the `Sysadmin` chapter, just after the `Installation` part https://libreant.readthedocs.io/en/latest/sysadmin.html.
If you are ok with it, I'm creating a new branch/PR to add this documentation. We're going down in the collaboration hell

**Comment by ael-code** [comment]
On 07/10/2016 03:15 PM, BoySka wrote:
> Inside the |Sysadmin| chapter, just after the |Installation| part
> https://libreant.readthedocs.io/en/latest/sysadmin.html.
> If you are ok with it, I'm creating a new branch/PR to add this
> documentation. We're going down in the collaboration hell

Great :)

**Comment by boyska** [comment]
Hey, I'm confused on what to do: our `setup.py` still says `elasticsearch >=1, < 2` which means that just running `python setup.py install` would not support elasticsearch2. Shall I suggest to force the upgrade to elasticsearch2? Shall we change the `setup.py` ?

**Comment by ael-code** [comment]
On 07/10/2016 03:52 PM, BoySka wrote:
> Hey, I'm confused on what to do: our |setup.py| still says
> |elasticsearch >=1, < 2| which means that just running |python setup.py
> install| would not support elasticsearch2. Shall I suggest to force the
> upgrade to elasticsearch2? Shall we change the |setup.py| ?


Didn't we already discussed about it on #301 [1] ?



[1] https://github.com/insomnia-lab/libreant/issues/301

**Comment by boyska** [comment]
Moving this to #304 . Sorry for the mess.

**Pull request merged**
