### PR TITLE
README: migration from `mdwn` to `rst`

### PR DESCRIPTION
**Pull request by ael-code**

### CODE REVIEW

**Comment by boyska** [comment]
how have you checked that the syntax is correct? is there something that can convert rst to html? (I know I could google it, but I am lazy!)

**Comment by boyska** [comment]
this is broken, because readme.mdwn is mentioned in `setup.py`

**Comment by boyska** [comment]
I found how to create the html.
```sh
python setup.py --long-description | rst2html
```

thus you can save it with
```sh
python setup.py --long-description | rst2html > /tmp/readme.html
```

or open it (if you use zsh) with

```sh
firefox =(python setup.py --long-description | rst2html)
```

sorry for so many comments

**Comment by ael-code** [comment]
> how have you checked that the syntax is correct? is there something that can convert rst to html? (I know I could google it, but I am lazy!)

You can simply check syntax through github on the [branch page](https://github.com/ael-code/libreant/blob/129_README_to_rst/README.rst)

**Comment by boyska** [comment]
On Fri, Mar 20, 2015 at 08:29:51AM -0700, ael wrote:
>> how have you checked that the syntax is correct? is there something that can convert rst to html? (I know I could google it, but I am lazy!)
>
>You can simply check syntax through github on the [branch page](https://github.com/ael-code/libreant/blob/129_README_to_rst/README.rst)

ahah you're right

**Comment by ael-code** [comment]
> this is broken, because readme.mdwn is mentioned in setup.py

modified also ```setup.py``` and ```MANIFEST.in```

**Pull request merged**
