### PR TITLE
attachments identification

### PR DESCRIPTION
**Pull request by ael-code**
these changes put the bases to introduce archivant package

The first commit modify only the name of the array containing attachments metadata:
`_files` -> `_attachments`
the real change was made to `webant/webant.py` the other changes are for propagation.

The second commit is the major one.
Before this p.r. we used to identified attachments with a pair: `<volumeID, array_position> ` but the array_position of an attachment could vary due to insertion/deletion of other attachment.
We decided to use an uuid4 to identify an attachment.
This migration will come in handy also if we will structure attachment like child document.

*look at the commits message for details*

### CODE REVIEW

**Comment by boyska** [comment]
why do you labeled  it "blocking" ? you say that this is blocking for the next release? do we have a plan for it?

**Comment by ael-code** [comment]
blocking for archivant introduction

**Comment by ael-code** [comment]
To test this function you can try to use the web UI to insert a volume with an attachment and then retrive the file attached to it. The details page and the search one should dislay correct informations about attachments. If these things and standard tests works correctly we can proceed with merging.
If you need additional details...ask!

**Comment by g3-3k** [comment]
Checked.
It runs 90 test and I verified the download of attachment.
Just I wonder of:
def test_download_count_mandatory(): 
You ask for download count but you furnish wrong name of attachment.

except this we can merge.

**Comment by boyska** [comment]
@g3-3k see the decorator `raises`? It actually changes the way the test is run, so that raising an exception means PASSING and not raising an exception means FAILING.
The test is exactly checking with wrong arguments it should raise exceptions.
Still, I have a doubt, too: what is that test checking **exactly**? Passing an invalid attachmentID should make it fail? Passing a valid attachmentID which points to an attachment without `download_count` should fail (as the function name implies)?

**Comment by boyska** [comment]
@ael-code seems that merging #137 made this untrivial to merge. Could you please rebase?

**Comment by boyska** [comment]
@ael-code sorry for so many replies; I think that my `attachments_id` branch contains a properly rebased commit. You may want to check, though.

**Comment by g3-3k** [comment]
boyska's attachment_id works on mine.
what have you changed?

**Comment by ael-code** [comment]
On 05/18/2015 11:46 PM, BoySka wrote:
> (...)
> Still, I have a doubt, too: what is that test checking *exactly*?
> Passing an invalid attachmentID should make it fail? Passing a valid
> attachmentID which points to an attachment without |download_count|
> should fail (as the function name implies)?

The answer is:
Passing a valid attachmentID which points to an attachment without
|download_count| should fail.

But I understood what you mean. This test could pass also if something
else goes wrong. It's not a wrong test, but maybe trivial.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by ael-code** [comment]
On 05/19/2015 12:01 AM, BoySka wrote:
> @ael-code <https://github.com/ael-code> sorry for so many replies; I
> think that my |attachments_id| branch contains a properly rebased
> commit. You may want to check, though.

I've checked and seems you did the right thing :)

Anyway now it's rebased, you can proceed with merging.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by ael-code** [comment]
Ops... I've accidentally last test line at `libreantdb/test/test_update.py:59`

**Comment by ael-code** [comment]
> Ops... I've accidentally last test line at libreantdb/test/test_update.py:59

fixed

**Comment by boyska** [comment]
>But I understood what you mean. This test could pass also if something
>else goes wrong. It's not a wrong test, but maybe trivial.

exactly; not a blocker, though.
I have not tested it myself, but I trust g3-3k. So can we merge?

**Comment by boyska** [comment]
Ok, I both run the unit tests and manually tried the tests you proposed in comment https://github.com/insomnia-lab/libreant/pull/142#issuecomment-103012419
so I'm pressing the Big Green Button!

**Pull request merged**
