### PR TITLE
Add language autocompletion

### PR DESCRIPTION
**Pull request by leonaard**
Closes \#284

### CODE REVIEW

**Comment by boyska** [comment]
what happens if `navitgator.language` is empty, or if its value cannot be found in the language list?

except for this corner cases, seems good

**Comment by leonaard** [comment]
it just disappears the placeholder string

**Comment by boyska** [comment]
leonaard:
>it just disappears the placeholder string

yeah, but I guess that if the user submit the volume, it could be with
an empty language, or with an invalid langcode

**Comment by leonaard** [comment]
the browser doesnt submit the form if there is no valid language, try it

**Comment by boyska** [comment]
leonaard:
>the browser doesnt submit the form if there is no valid language, try it

I tried and it does. Since there is no practical way of forcing an
invalid language in firefox, I manually opened the firebug console and
typed `document.getElementById('language').value = 'zz';`
I sumbitted it, and it is added. I think that this should be prevented
client-side (server-side we should accept any two-letter code).

**Comment by boyska** [comment]
Oh, wait; it used to have the bug I reported, but now I see that everything is working fine, o0

merging

**Pull request merged**
