### PR TITLE
Add book

### PR DESCRIPTION
**Pull request by ael-code**
implemented system to upload items to libreant, general restyling

I have tried to implement all functionality introduced by @frenko on his [fork](https://github.com/frenko/libreant/). @frenko you should check if I am missing something.

#### New route:
 - /add ( POST | GET )
 - /download/{bookid}/{fileid}

#### New pip dependecies:
 - Fsdb ;)

#### Open points:
 - how to handle Fsdb path

( more details are coming )

#### Attention:
 - commit 19ab11b4866a6911c8201804215a5beb857e398e breaks the stuff to import other libraries: ```language``` was updated to ```_language``` and we should do the same thing with ```text_*```

### CODE REVIEW

**Comment by boyska** [comment]
why closing this?

btw: I started reviewing this, but the incredibly high number of commits make it a bit difficult to review. I will much appreciate some "squashing" of similar commits. In the same spirit, I would be happy if you could avoid unneeded changes not pertinent to the "add book". For example, I see that there is:

* some restyling
* routes for downloading books (`/download/blabla`)
* changes on the `/view/<bookid>`
* changes on how the FTS is done

... and I still haven't finished reviewing!
I know that sometime it is very difficulto to make "atomic" commits, and touching related things seems natural but... please don't go too far.

**Comment by ael-code** [comment]
I'll try to cleanup the commit tree.

**Comment by ael-code** [comment]
moved all FTS code on #13.
waiting for merge of that branch to rebase this one.

**Comment by boyska** [comment]
Because of https://github.com/insomnia-lab/libreant/pull/22#issuecomment-69839205 I am closing this

**Pull request closed without merging**
