### PR TITLE
Securing REST api

### LINKED ISSUE #287: Securing REST api
We can start discussing here on how to secure the REST api.

If you want to read something:
https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Authentication_and_session_management
http://stackoverflow.com/questions/319530/restful-authentication

### PR DESCRIPTION
**Pull request by ael-code**
This PR should fix #287.

I've added the authentication layer also to all the REST endpoints. I've implemented the simplest approach: the authentication method is the same used for the rest of the libreant web ui. This means that in order to use a restricted REST endpoint you should have been authenticated through the `/login` page.

As we've already discussed with @boyska in #287 this is doesn't respect the REST paradigm at all, but it works and it should be enough to fix the security issue.

We had a lot of old test functions that were used to test the REST api, in order to make them continue to work I've managed to execute them as the admin user that has all the capabilities granted by default.

Probably we need some more tests against the authorization layer, I really hope that some contribution for that will arrive.

### CODE REVIEW

**Comment by boyska** [comment]
cool! Some early questions:
* what is `TransparentAuth` ? is it some sort of aggregator of multiple ways of authentication (like session + basic auth + ip + whatever) ?
* could we have some test showing that some api do not need login while some do? not that this will prove that it is perfectly secure, but that at least the authorization layer is somewhat effective.

**Comment by ael-code** [comment]
On 06/25/2016 10:46 PM, BoySka wrote:
> cool! Some early questions:
> 
>   * what is |TransparentAuth| ? is it some sort of aggregator of
>     multiple ways of authentication (like session + basic auth + ip +
>     whatever) ?

In the case we run Libreant in single-user-mode (without passing the
`--users-db` option ), we use `TransparentAuth*`:
```
        if self.users_enabled:
            self.autht = auth.AuthtFromSessionAnon()
            self.authz = auth.AuthzFromSession(authenticator=self.autht)
        else:
            self.autht = auth.TransparentAutht()
            self.authz = auth.TransparentAuthz()
```

The `TransparentAuth*` implements authentication/authorization
interfaces with only no-op functions, this allow us to write code that
implements the authentication layer but give us the possibility to skip
it when we are in single-user-mode.

>   * could we have some test showing that some api do not need login
>     while some do? not that this will prove that it is perfectly secure,
>     but that at least the authorization layer is somewhat effective.
> 

I was expecting this :) . All the REST api about users requires the
client to be logged in because the anonymous user doesn't have any
default capability upon users stuff. I've wrote only two sample test on
the `add_user` endpoint to test if the Auth layer is working properly

**Comment by boyska** [comment]
I'm slightly confused about the test, then. What is it exactly calling? I would expect the test to recall something like "perform a POST on this URL, and expect a 403", so very black-box, but it appears that it is different.

Also, shouldn't it be 403, not 401? 401 is when the user is expected to login. Our message should be about authorization only, so 403

**Comment by ael-code** [comment]
> I'm slightly confused about the test, then. What is it exactly calling? I would expect the test to recall something like "perform a POST on this URL, and expect a 403", so very black-box, but it appears that it is different.

I've added two new tests:
 - `test_add_user_as_anon`: in this one we try to add a new user without the proper capability to do that and we should receive a 403.

 - `test_add_user_with_capability`: in this one we first create a user/group with the proper capability, login with that user and then try to add a new user. This time we should receive a successful response since we are allowed to do that.

> 
> Also, shouldn't it be 403, not 401? 401 is when the user is expected to login. Our message should be about authorization only, so 403

Yeap, you're right. Fixed.

**Comment by boyska** [comment]
seems good, just rebase & merge it

**Comment by boyska** [comment]
ael:
>Merged #296.

I think that time is ready to release libreant 0.5: we have a bunch of
good improvements, especially this one and the support for
elasticsearch2, which we'd better roll out as soon as possible.

PS: yeah, sorry, I didn't know what was the right place to post this
proposal.

**Comment by ael-code** [comment]
On 07/10/2016 12:04 PM, BoySka wrote:
> ael:
>>Merged #296.
> 
> I think that time is ready to release libreant 0.5: we have a bunch of
> good improvements, especially this one and the support for
> elasticsearch2, which we'd better roll out as soon as possible.
> 
> PS: yeah, sorry, I didn't know what was the right place to post this
> proposal.

WIP

**Pull request merged**
