### PR TITLE
Clean leftovers

### PR DESCRIPTION
**Pull request by boyska**
We have lot of stuff that was there since ages, but is actually not needed anymore. This is mostly shell scripts, but we found better solutions for them.

### CODE REVIEW

**Comment by hellais** [comment]
Buy run_all_dev and run_es are mentioned in the docs: https://github.com/insomnia-lab/libreant#run. If they are deprecated the docs should also be updated with the new command.

**Comment by boyska** [comment]
oh god, I thought I would have some seconds to push those new commits.
Ok now I think to be done.

**Comment by hellais** [comment]
LOL. Sorry :P

**Comment by ael-code** [comment]
I'm not sure we can delete babel scripts.

**Comment by boyska** [comment]
On Tue, Feb 24, 2015 at 10:07:04AM -0800, ael wrote:
>I'm not sure we can delete babel scripts.

me neither. But I tried with a clean `python setup.py develop` and it
appears to work. I don't know if there is any other usecase for those
script, I'd like to know it from you!

**Comment by ael-code** [comment]
> me neither. But I tried with a clean `python setup.py develop` and it appears to work. I don't know if there is any other usecase for those script, I'd like to know it from you !

except for ```webant/babel/trans_compile.sh``` we need them.

**Comment by boyska** [comment]
@ael-code updated following your suggestions

**Comment by ael-code** [comment]
you should include also 77a73e15c3c71da2fe3d6502fe33924ba96b97a1 that removes elasticsearch folder with  local config

**Comment by boyska** [comment]
done

**Pull request merged**
