### PR TITLE
Preset template

### PR DESCRIPTION
**Pull request by leonaard**
now you can specify in the preset which template to use to render the corresponding volumes

### CODE REVIEW

**Comment by ael-code** [comment]
When you don't want to use a specific template you should leave empty the template field in the preset.
Therefore, commit b2760e6 should be reverted in my opinion.

**Comment by ael-code** [comment]
f004e70 has introduced some flake8 issue on [presets/presetManager.py](https://github.com/leonaard/libreant/blob/f004e7047b0334ec8a05e4682208aea50eb255b1/presets/presetManager.py#195)

```
$ flake8 presets/presetManager.py --ignore=E501

presets/presetManager.py:196:1: E101 indentation contains mixed spaces and tabs
presets/presetManager.py:196:1: W191 indentation contains tabs
presets/presetManager.py:196:4: E126 continuation line over-indented for hanging indent
presets/presetManager.py:197:1: W191 indentation contains tabs
presets/presetManager.py:198:1: W191 indentation contains tabs
presets/presetManager.py:198:3: E126 continuation line over-indented for hanging indent
presets/presetManager.py:199:1: E101 indentation contains mixed spaces and tabs
```

**Comment by leonaard** [comment]
have a look now

**Comment by boyska** [comment]
I am not very happy with this "concept": the fact that a preset is not just a declarative definition of a form, but is actually a _type_ is a bit strange to me.

I think of this scenario:
1. The librarian creates a `book` preset, which asks for title, actors and editor.
2. Someone creates _La conquista del pane, Kroptokin, Nautilus edizioni_
3. later, a librarian creates a new preset called `politics books`

Now _la conquista del pane_ has the wrong preset, and there's no way to move it, because the difference between a book and a politics book is not in the metadata, but in the type.

You could say: so let's add a tool to change the type of a book. But this is
* difficult to do decently. How would you check that the metadata are still correct for the new type?
* just a workaround

I believe that the template should be customized depending on the metadata of a volume. This makes more sense because:
* metadata are a "public" fact
* this setting is richer (for example one can add a template for every volume with an attachment, or one for every volume which contains some specific word in some fields, ie: _Fortepressa_ in the actors field)
* it's more duck-typed
* is not any less practical. If someone wants to create a form that automatically put its volumes into some sort of "category", she just needs to add a hidden field to the preset specifying something like `category=comics`. This way it is obvious to create a template for books created by that preset, but still the two things are decoupled.

I love ducks.

**Comment by leonaard** [comment]
> the template should be customized depending on the metadata of a volume.
now you can do this

**Comment by boyska** [comment]
On Sat, Jun 27, 2015 at 09:52:22AM -0700, leonaard wrote:
>> the template should be customized depending on the metadata of a volume.
>now you can do this

mh, I probably wrote something different than what I intended. I meant
the template should be __chosen__ depending on the metadata of a volume.
So I imagine a simple way to associate a template with a
condition on volume metadata.

**Comment by leonaard** [comment]
ok now i got it

imo we can just add a user configurable dictionary to link the volumes
`category` field to a given template

any better ideas?

**Comment by leonaard** [comment]
Any updates on this? @boyska i think we can merge this and keep your ideas for a future implementation.

**Comment by boyska** [comment]
My concern is that now I don't know what's a "preset" anymore. Wasn't it a way to specify a form?

why should it define a "kind" of volume? I see this coupling as a serious design flaw.

**Comment by leonaard** [comment]
So is it ok if we select a template only from the `_template` field in
the volume object (not from the `_preset` one)?

**Comment by ael-code** [comment]
On 07/12/2015 06:06 PM, leonaard wrote:
> So is it ok if we select a template only from the `_template` field in
> the volume object (not from the `_preset` one)?
> 

I will choose this solution for now.
Store the template id inside the volume object under `_template` key
seems a simple solution.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by leonaard** [comment]
i updated the pr

**Comment by ael-code** [comment]
What happens if the file does not exists?

**Pull request closed without merging**
